### ISSUE TITLE
Module["dynCall_*"] is not a function

### ISSUE THREAD

**Issue by galileolajara** [emscripten-core/emscripten#25560]
**Version of emscripten/emsdk:**
4.0.15

After upgrading from 4.0.0 to 4.0.15, compiling my app that relies on dynCalls doesn't work with the following runtime error on the browser: ``Module["dynCall_*"] is not a function``

This bug is not occuring in 4.0.0.

In 4.0.15, I fixed it by creating a python script that replaces ``Module["dynCall_*"](...)`` with ``dynCall(...)`` on the output .js file. These calls to ``Module["dynCall_*"]`` are found in ``invoke_*`` functions. For example:
```
function invoke_vid(index,a1,a2) {
  var sp = stackSave();
  try {
    Module["dynCall_vid"](index,a1,a2); // This must be changed to dynCall_vid(index,a1,a2);
  } catch(e) {
    stackRestore(sp);
    if (e !== e+0) throw e;
    _setThrew(1, 0);
  }
}
```

I hope the bug fix makes it to the next release.

**Comment by pixelomer** [comment]
Could this be related to #25551? It looks like the example I shared in that issue works on version 4.0.0 while it fails on version 4.0.16.

**Comment by sbc100** [comment]
Can you confirm if you are building with `-sMAIN_MODULE`?

If you are able could you try to bisect to figure out when this broke: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by sbc100** [comment]
I think the cause if the issue is #24797
