### ISSUE TITLE
Unreachable inside unwinding

### ISSUE THREAD

**Issue by MizantropLoL** [emscripten-core/emscripten#14770]
There is an app that successfully worked with emscripten v1.38.30. After updating emscripten to actual version (2.0.25) and fixing compilation errors, runtime errors, this exception occurs:
RuntimeError: abort(RuntimeError: unreachable) at Error
    at jsStackTrace (http://localhost:6931/index.js:2697:14)
    at stackTrace (http://localhost:6931/index.js:2712:11)
    at abort (http://localhost:6931/index.js:1514:43)
    at runAndAbortIfError (http://localhost:6931/index.js:16700:3)
    at Object.maybeStopUnwind (http://localhost:6931/index.js:16781:4)
    at ret.<computed> (http://localhost:6931/index.js:16767:18)
    at Object.doRewind (http://localhost:6931/index.js:16814:10)
    at http://localhost:6931/index.js:16838:41
    at callUserCallback (http://localhost:6931/index.js:6272:3)
    at http://localhost:6931/index.js:6285:3
    at abort (http://localhost:6931/index.js:1516:10)
    at runAndAbortIfError (http://localhost:6931/index.js:16700:3)
    at Object.maybeStopUnwind (http://localhost:6931/index.js:16781:4)
    at ret.<computed> (http://localhost:6931/index.js:16767:18)
    at Object.doRewind (http://localhost:6931/index.js:16814:10)
    at http://localhost:6931/index.js:16838:41
    at callUserCallback (http://localhost:6931/index.js:6272:3)
    at http://localhost:6931/index.js:6285:3
Main loop implemented with emscripten_sleep.
Any ideas or hints to solve this one?

**Comment by kripken** [comment]
That's a huge range of changes - it includes a complete replacement of the LLVM backend, in particular. I'd suggest bisecting to figure this out in the fastest way,

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

Otherwise, that could be an assertion from the new Asyncify. Viewing the code around that failing assertion could help, in a debugger.

**Comment by MizantropLoL** [comment]
The oldest version with that error is v1.38.39-upstream. In v1.38.38-upstream I've got error in _emscripten_sleep - Module['setAsync'] is not exist.

I found out that setAsync adds in Module only when fastcomp backend used.
Is my suggection correct? I may missed some flag or anything, can you advise? Should I bisect v1.38.39-upstream?

Thank you.
