### ISSUE TITLE
Error : redefinition of '__em_asm_sig' when upgrading from 2.0.6 to 2.0.15

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#13629]
I am trying to upgrade emsdk version from 2.0.6 to 2.0.15(latest). I have encountered a strange redefinition error which was not there in 2.0.6

```
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(100,44): error : redefinition of '__em_asm_sig' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<typename, typename = void> struct __em_asm_sig {};
                                             ^
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(100,44):  note: previous definition is here
  template<typename, typename = void> struct __em_asm_sig {};
```

I think the issue is both `EM_CACHE` directory (which is set to `C:\emsdk-portable-64bit\2.0.15`) and default cache location (`C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache`) is being searched and hence the redefinition error. I tried clearing cache using `emcc --clear-cache` but that didn't solve the issue.  I also noticed there were some cache related changes in 2.0.13. I suspect those changes have some relation with the above error.

**Comment by sbc100** [comment]
This should certainly not happen.  Only the EM_CACHE directory should be included (via the `--sysroot` command line flag to clang).

Can you post the full emcc command and the full error (which should include the full clang command that failed?)

As a side node, how are you installing emscripten and emsdk.. where is the path C:\emsdk-portable-64bit\2.0.15 coming from?  Why not just use the default cache location?

**Comment by ravisumit33** [comment]
> This should certainly not happen. Only the EM_CACHE directory should be included (via the `--sysroot` command line flag to clang).
> 
> Can you post the full emcc command and the full error (which should include the full clang command that failed?)
> 
> As a side node, how are you installing emscripten and emsdk.. where is the path C:\emsdk-portable-64bit\2.0.15 coming from? Why not just use the default cache location?

I have installed emsdk by cloning the repo using git and using install and activate commands. We have environment variable `EM_CACHE` set to `C:\emsdk-portable-64bit\2.0.15` so this path is coming. We are using this location for a long time and no issue was there. 

Below is the full emcc command (trimmed down to relevant info):
```
emcc -o fontSupport.o  -std=gnu++11 -pedantic-errors -MD -MF fontSupport.d -Oz -include-pch pch.pch -c -std=c++14 -fPIC -s DISABLE_EXCEPTION_CATCHING=2 -s EXCEPTION_CATCHING_ALLOWED=@ExceptionCatchingWhitelist.txt -Wno-zero-length-array -Wno-gnu-zero-variadic-macro-arguments -Wno-dollar-in-identifier-extension -Wno-builtin-macro-redefined -x c++ fontSupport.cpp
```

Below is full error:
```
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(100,44): error : redefinition of '__em_asm_sig' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<typename, typename = void> struct __em_asm_sig {};
                                             ^
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(100,44):  note: previous definition is here
  template<typename, typename = void> struct __em_asm_sig {};
                                             ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(101,19): error : redefinition of '__em_asm_sig<float>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<float> { static const char value = 'd'; };
                    ^~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(101,19):  note: previous definition is here
  template<> struct __em_asm_sig<float> { static const char value = 'd'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(102,19): error : redefinition of '__em_asm_sig<double>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<double> { static const char value = 'd'; };
                    ^~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(102,19):  note: previous definition is here
  template<> struct __em_asm_sig<double> { static const char value = 'd'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(103,19): error : redefinition of '__em_asm_sig<char>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<char> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(103,19):  note: previous definition is here
  template<> struct __em_asm_sig<char> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(104,19): error : redefinition of '__em_asm_sig<signed char>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<signed char> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(104,19):  note: previous definition is here
  template<> struct __em_asm_sig<signed char> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(105,19): error : redefinition of '__em_asm_sig<unsigned char>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<unsigned char> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(105,19):  note: previous definition is here
  template<> struct __em_asm_sig<unsigned char> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(106,19): error : redefinition of '__em_asm_sig<short>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<short> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(106,19):  note: previous definition is here
  template<> struct __em_asm_sig<short> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(107,19): error : redefinition of '__em_asm_sig<unsigned short>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<unsigned short> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(107,19):  note: previous definition is here
  template<> struct __em_asm_sig<unsigned short> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(108,19): error : redefinition of '__em_asm_sig<int>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<int> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(108,19):  note: previous definition is here
  template<> struct __em_asm_sig<int> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(109,19): error : redefinition of '__em_asm_sig<unsigned int>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<unsigned int> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(109,19):  note: previous definition is here
  template<> struct __em_asm_sig<unsigned int> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(110,19): error : redefinition of '__em_asm_sig<long>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<long> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(110,19):  note: previous definition is here
  template<> struct __em_asm_sig<long> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(111,19): error : redefinition of '__em_asm_sig<unsigned long>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<unsigned long> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(111,19):  note: previous definition is here
  template<> struct __em_asm_sig<unsigned long> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(112,19): error : redefinition of '__em_asm_sig<bool>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<bool> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(112,19):  note: previous definition is here
  template<> struct __em_asm_sig<bool> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(113,19): error : redefinition of '__em_asm_sig<wchar_t>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_sig<wchar_t> { static const char value = 'i'; };
                    ^~~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(113,19):  note: previous definition is here
  template<> struct __em_asm_sig<wchar_t> { static const char value = 'i'; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(114,29): error : redefinition of '__em_asm_sig<T *>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<typename T> struct __em_asm_sig<T*> { static const char value = 'i'; };
                              ^~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(114,29):  note: previous definition is here
  template<typename T> struct __em_asm_sig<T*> { static const char value = 'i'; };
                              ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(117,23): error : redefinition of '__em_asm_if' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<bool> struct __em_asm_if { };
                        ^
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(117,23):  note: previous definition is here
  template<bool> struct __em_asm_if { };
                        ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(118,19): error : redefinition of '__em_asm_if<true>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<> struct __em_asm_if<true> { typedef void type; };
                    ^~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(118,19):  note: previous definition is here
  template<> struct __em_asm_if<true> { typedef void type; };
                    ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(119,29): error : redefinition of '__em_asm_sig<T, typename __em_asm_if<__is_enum(T)>::type>' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  template<typename T> struct __em_asm_sig<T, typename __em_asm_if<__is_enum(T)>::type> {
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(119,29):  note: previous definition is here
  template<typename T> struct __em_asm_sig<T, typename __em_asm_if<__is_enum(T)>::type> {
                              ^
  C:\Users\sumik\AcroJS\Compiler_Upgrade\t4\libs\tetraphilia\pdf\text\AcrobatJS\acrobatJSFontSupport.cpp(42): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten.h(1): includes this header: 
  C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\emscripten.h(23): includes this header: 
C:\emsdk-portable-64bit\2.0.15\sysroot\include\emscripten\em_asm.h(125,8): error : redefinition of '__em_asm_type_tuple' [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  struct __em_asm_type_tuple {};
         ^
  C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h(125,8):  note: previous definition is here
  struct __em_asm_type_tuple {};
         ^
GCCCOMPILE : fatal error : too many errors emitted, stopping now [-ferror-limit=] [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
  20 errors generated.
emcc : error : 'C:/Users/sumik/latest_emsdk/emsdk/upstream/bin\clang++.exe -DEMSCRIPTEN -fno-inline-functions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -emscripten-cxx-exceptions-allowed=eventHandler,handleRegisterLicense,_ZN2t33pdf11textextract14TextDLConsumerINS_20TetraphiliaAppTraitsEE32ConsumeContentUntilDoneOrStoppedERNS0_7content11DisplayListIS3_EE,_ZN2t33pdf11textextract14TextDLConsumerINS_20TetraphiliaAppTraitsEE32ConsumeContentUntilDoneOrStoppedINS0_7content23TransactibleDisplayListIS3_EEEEvRT_,_ZN2t33pdf11textextract14TextDLConsumerINS_20TetraphiliaAppTraitsEE32ConsumeContentUntilDoneOrStoppedINS0_8document15PageDisplayListIS3_EEEEvRT_,_ZN2t33pdf8document6detail12TreeFindFastINS2_16NumberTreeLookupEEEN5boost8optionalINS2_8tree_posINT_11tree_traitsEEEEERKNS0_5store10DictionaryINSC_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEEERKNS8_11tree_traits14param_key_typeE,_Z16AJSReverseLookupN2t44sptrIN2t33pdf4text11CharCodeMapEEEDsRNS3_21CharCodeReverseLookupE -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -iwithsysroot/include/SDL -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=15 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -flegacy-pass-manager -Werror=implicit-function-declaration --sysroot=C:\emsdk-portable-64bit\2.0.15\sysroot -Xclang -iwithsysroot/include\compat -D__declspec(x)= -D__stdcall= -D__int64=int64_t -D__int8=int8_t -D__int16=int16_t -D__int32=int32_t -DNDEBUG -D_ITERATOR_DEBUG_LEVEL=0 -DNOMINMAX -DWIN_ENV -DTETRAPHILIA_CUSTOM_CMYK_TO_RGB -DTETRAPHILIA_SUPPORT_JBIG2 -DJBIG2_LIBRARY -DTETRAPHILIA_SUPPORT_JP2K_DLL -Dtetraphilia=t3 -DCRYPTOPENSSL_EXCLUDED -DWIN32 -DTETRAPHILIA_PDF_PERMISSIVE -DTETRAPHILIA_T3_COMPAT -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_NO_DEPRECATED -D_UNICODE -DUNICODE -DUSE_SYSTEM_FONTS=1 -DEMSCRIPTEN=1 -DBOOST_NO_EXCEPTIONS=1 -DBOOST_EXCEPTION_DISABLE=1 -DEMSCRIPTEN_REMOVE_DEAD_CODE=1 -DSUPPORT_PDF_EDIT=1 -DSUPPORT_PDF_TRANSACTIONS=1 -std=gnu++11 -pedantic-errors -DEMSCRIPTEN -D__STDC__ -MD -MF ../../BuildResults/t4/Emscripten/SHIP_LITE/acrobatjs/acrobatjs/../../t4/libs/tetraphilia/pdf/text/AcrobatJS//acrobatJSFontSupport.d -Oz -I../../T4ObjectBridge/headers/ajs -I../../t4/thirdparty/freetype/include -I../../t4/thirdparty/range-v3/include -I../thirdparty -I../t4/thirdparty/md5 -I../libs/uft/uft/public -I../libs -I../libs/openssl-1.0.2h/include -I../../t4/thirdparty/libxml2/include -I../../t4 -I../../t4/thirdparty/boost_libraries -I../libs/threadpool -I../../t4/t4/ -I../../t4/t4/tetraphilia/acro_compat -I../../t4/firstparty -I../../t4/thirdparty -I../projects/libjpeg/xcode/include -I../thirdparty/libjpeg -I../thirdparty/libjpeg/sources -I../../t4/firstparty/edc/PDRLLib/Public/Headers -I../../t4/firstparty/edc/EDCClientLib/Public/Headers -I../../t4/firstparty/edc/EDCClientLib/Source -I../../t4/firstparty/acemobile/headers -I../../t4/firstparty/acemobile/headers/win32 -IC:/Users/sumik/AcroJS/Compiler_Upgrade/acrobatjs/t4/ "-IGenerated Files/" -I../../BuildResults/t4/Emscripten/SHIP_LITE/ -I../../t4/t4/tetraphilia/Emscripten -I../../t4/thirdparty/nlohmann/include -Iheaders -I../libs/rapidjson/include -I../../t4/t4/pdf -I../../t4/firstparty/aide/public/include/api -I../../t4/firstparty/aide/source/aide/aide-core/inc -I../../t4/firstparty/aide/source/aide/gif/headers -I../../t4/firstparty/aide/source/aide/bmp/headers -include-pch ../../BuildResults/t4/Emscripten/PCH_SHIP/pch.pch -c -std=c++14 -fPIC -DWASM_DYNAMIC_LINKING -DENFORCE_CLIENT_DOMAIN_WHITELIST -Wno-zero-length-array -Wno-gnu-zero-variadic-macro-arguments -Wno-dollar-in-identifier-extension -Wno-builtin-macro-redefined -x c++ ../../t4/libs/tetraphilia/pdf/text/AcrobatJS/acrobatJSFontSupport.cpp -o ../../BuildResults/t4/Emscripten/SHIP_LITE/acrobatjs/acrobatjs/../../t4/libs/tetraphilia/pdf/text/AcrobatJS//acrobatJSFontSupport.o' failed (1) [C:\Users\sumik\AcroJS\Compiler_Upgrade\acrobatjs\t4\t4.vcxproj]
```

As can be seen above, there are too many redefinition errors. Also in the full clang command, we can see `--sysroot=C:\emsdk-portable-64bit\2.0.15\sysroot ` which suggests that sysroot is set to the directory where `EM_CACHE` environment variable is pointing to.

**Comment by sbc100** [comment]
Right.. so it looks like EM_CACHE is working as expected.. which is good.    Looking at your clang command I can't see how anything from the emsdk directory would ever be included. 
 The conflict is due to including files under `C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\`  .. but I can't see the word `cache` anywhere in you clang command line.

Can you see how `C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\sysroot\include\emscripten\em_asm.h` is being include?   Perhpas at a `#error` to top that file and see how is trying to include it... I can't see how clang would find that file unless it was being included via some relative or absolute path.

**Comment by sbc100** [comment]
Oh, maybe it might be perhaps related to use of PCH?    I see `-include-pch ../../BuildResults/t4/Emscripten/PCH_SHIP/pch.pch` .. perhaps that needs to be rebuilt?

**Comment by ravisumit33** [comment]
Yes, you are right. Default cache location was included since `EM_CACHE` environment was not set during pch build. I have corrected it and errors are gone. Thanks :)
