### ISSUE TITLE
EXTRA_EXPORTED_RUNTIME_METHODS vs EXPORTED_RUNTIME_METHODS

### ISSUE THREAD

**Issue by domoritz** [emscripten-core/emscripten#13812]
I haven't found an explanation of the difference in the docs. Could you elaborate and add it to the docs?

**Comment by kripken** [comment]
Which docs did you read?

There is a comment in settings.js,

https://github.com/emscripten-core/emscripten/blob/64011e101e56cf713825d2d6e0a74a41f95d96c8/src/settings.js#L788-L800

**Comment by domoritz** [comment]
Ahh, I missed that. 

https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html references EXPORTED_RUNTIME_METHODS but the reso of the docs use EXTRA_EXPORTED_RUNTIME_METHODS so I got confused.

See https://emscripten.org/search.html?q=EXTRA_EXPORTED_RUNTIME_METHODS&check_keywords=yes&area=default# vs https://emscripten.org/search.html?q=EXPORTED_RUNTIME_METHODS&check_keywords=yes&area=default

**Comment by kripken** [comment]
Those docs could be improved, I agree.

A PR would be great!

**Comment by sbc100** [comment]
Shouldn't we prefer to just deprecate `EXTRA_EXPORTED_RUNTIME_METHODS`?   Is doesn't serve any purpose no that `EXPORTED_RUNTIME_METHODS` is empty by default, rigth?

**Comment by sbc100** [comment]
WIP example to see if deprecation works: https://github.com/emscripten-core/emscripten/pull/13895

**Comment by sbc100** [comment]
Hopefully this closed by #13895

**Comment by cajus** [comment]
Just a question: 'EXTRA_EXPORTED_RUNTIME_METHODS' is deprecated now, but if I use (2.0.19)

```
add_link_options("SHELL:-s EXPORTED_RUNTIME_METHODS=ccall,cwrap")
```

in my CMake configuration, I'm getting `Uncaught TypeError: Module.cwrap is not a function` when loading the page. Although the docs suggest that I've just to exchange the names, that doesn't seem to work here.

**Comment by sbc100** [comment]
Hmm.. that sounds like a bug.  I surprised the handling of EXPORTED_RUNTIME_METHODS did not really change.    Did it work in 2.0.18?   Is the `cwap` function function being included but not exported?   Could you attach the full output your link with `EMCC_DEBUG` enabled perhaps?

**Comment by sbc100** [comment]
We have quite a few tests that include cwrap via EXPORTED_RUNTIME_METHODS:

```
$ git grep EXPORTED_RUNTIME_METHODS.*cwrap tests/
tests/test_browser.py:    self.btest(os.path.join('browser', 'cwrap_early.cpp'), args=['-O2', '-s', 'ASSERTIONS', '--pre-js', test_file('browser', 'cwrap_early.js'), '-s', 'EXPORTED_RUNTIME_METHODS=[cwrap]'], expected='0')
tests/test_core.py:    self.set_setting('EXPORTED_RUNTIME_METHODS', ['ccall', 'cwrap'])
tests/test_core.py:    self.set_setting('EXPORTED_RUNTIME_METHODS', ['ccall', 'cwrap'])
tests/test_other.py:                      '-s', 'EXPORTED_RUNTIME_METHODS=ccall,cwrap',
tests/test_other.py:                      '-s', 'EXPORTED_RUNTIME_METHODS=ccall,cwrap',
tests/test_other.py:                      '-s', 'EXPORTED_RUNTIME_METHODS=ccall,cwrap,FS,PROXYFS',
```

**Comment by cajus** [comment]
Just updated from 2.0.17 to 2.0.19 and changed that one thing. I'll look for the linker output.

**Comment by sbc100** [comment]
Thanks, I don't doubt there is bug here.. thanks for helping us find it.     If you could check 2.0.18 that would be useful too.

**Comment by cajus** [comment]
2.0.18 doesn't work either. I've placed everything after/including the linking stage [here](https://ferdi.naasa.net/log-2.0.18.txt), maybe you can see something strange there.

**Comment by sbc100** [comment]
Ah, you are specifying `-s EXPORTED_RUNTIME_METHODS` twice on the command line .. the second time with an empty list.  That will do it :)

**Comment by sbc100** [comment]
Also, you can skip the `SHELL:` nastiness in cmake these day by removing the space between the `-s` and the option name.

**Comment by cajus** [comment]
Ouops. So I'll have to find out who's adding the second one. It's not in my CMakeLists - maybe Qt brings it in. I'll find out when I'm back in the office. Thanks for your investigation!
