### PR TITLE
Disable `-Wcast-function-type-strict` in HarfBuzz port

### PR DESCRIPTION
**Pull request by kleisauke**
Corresponds to the fix introduced in commit https://github.com/harfbuzz/harfbuzz/commit/60c6b7786d9f4651ae2803bfc4ff4435b38a5bc6. This should fix the LLVM autoroller.

Context: https://github.com/emscripten-core/emscripten/issues/16126#issuecomment-1295914949.

### CODE REVIEW

**Comment by kleisauke** [comment]
```
error: unknown warning option '-Werror=cast-function-type-strict'; did you mean '-Werror=cast-function-type'? [-Werror,-Wunknown-warning-option]
````
... a chicken-and-egg situation, commit 2034c204fa889af5cacb761167a7a5aaf1a02a90 should fix that.

**Review by kripken — APPROVED** [review]

**Comment by dschuff** [comment]
Thanks for this!
I tried it out locally with a fresh LLVM, and for some reason adding these flags it doesn't seem to suppress the warning. I'm getting
```
/usr/local/google/home/dschuff/s/emr/install/emscripten/cache/ports/harfbuzz/harfbuzz-3.2.0/src/hb-ft.cc:762:73: error: cast from 'void (*)(FT_Face)' (aka 'void (*)(FT_FaceRec_ *)') to 'FT_Generic_Finalizer' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
  if (unlikely (!ft_face->generic.data || ft_face->generic.finalizer != (FT_Generic_Finalizer) hb_ft_face_finalize))
                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/dschuff/s/emr/install/emscripten/cache/ports/harfbuzz/harfbuzz-3.2.0/src/hb.hh:248:46: note: expanded from macro 'unlikely'
#define unlikely(expr) (__builtin_expect (!!(expr), 0))
                                             ^~~~
/usr/local/google/home/dschuff/s/emr/install/emscripten/cache/ports/harfbuzz/harfbuzz-3.2.0/src/hb-ft.cc:768:34: error: cast from 'void (*)(FT_Face)' (aka 'void (*)(FT_FaceRec_ *)') to 'FT_Generic_Finalizer' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
    ft_face->generic.finalizer = (FT_Generic_Finalizer) hb_ft_face_finalize;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/dschuff/s/emr/install/emscripten/cache/ports/harfbuzz/harfbuzz-3.2.0/src/hb-ft.cc:1032:32: error: cast from 'void (*)(FT_Face)' (aka 'void (*)(FT_FaceRec_ *)') to 'FT_Generic_Finalizer' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
  ft_face->generic.finalizer = (FT_Generic_Finalizer) _release_blob;
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

From that output it certainly *seems* like it ought to be suppressed by the flag you added, but I don't know why it's not. I'll try a few other things; are you able to reproduce this?

**Comment by kleisauke** [comment]
Ah, I only verified whether this flag was passed to the HarfBuzz port and didn't test it locally with a fresh LLVM. I think this is due to that HarfBuzz enables `-Wcast-function-type` (which has `-Wcast-function-type-strict` as a subgroup) via pragmas - see:
https://github.com/harfbuzz/harfbuzz/blob/3.2.0/src/hb.hh#L67

Are you able to test PR https://github.com/emscripten-core/emscripten/pull/18125? I also defined `HB_NO_PRAGMA_GCC_DIAGNOSTIC_WARNING` to ensure `-Wextra` is disabled.

**Comment by dschuff** [comment]
Ah yes, that works, thanks. Also explains why I was confused looking at the warning flags (i.e. I didn't realize the warnings were being enabled by pragmas rather than by flags).
