### ISSUE TITLE
FreeImage cause em++ to crash when compiling

### ISSUE THREAD

**Issue by TV4Fun** [emscripten-core/emscripten#2067]
I am using a version of FreeImage 3.15.4 compiled from the main FreeImage repository with minor modification to the makefiles in order to compile with emscripten. When I attempt to compile a sample program with -Os and DISABLE_EXCEPTION_CATCHING=0 (either option works separately), it causes em++ to produce a JavaScript error, see below:

```
joel@Discrete:~/freeimage-test$ ../emscripten/em++ TextureManager.cpp freeImageTest.cpp -L. -lfreeimage -s DISABLE_EXCEPTION_CATCHING=0 -Os --save-bc out.bc

/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
        throw new JS_Parse_Error(message, line, col, pos);
              ^
TypeError: object is not a function
    at new JS_Parse_Error (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
    at js_error (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
    at croak (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
    at token_error (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
    at expect_token (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:762:17)
    at Object.expect (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:765:40)
    at Object.1 (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1307:38)
    at prog1 (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
    at /home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1100:51
    at maybe_unary (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1209:27)
Traceback (most recent call last):
  File "/home/joel/emscripten/emcc", line 2036, in <module>
    flush_js_optimizer_queue()
  File "/home/joel/emscripten/emcc", line 1967, in flush_js_optimizer_queue
    final = shared.Building.js_optimizer(final, js_optimizer_queue, jcache, debug_level >= 4, js_optimizer_extra_info)
  File "/home/joel/emscripten/tools/shared.py", line 1404, in js_optimizer
    return js_optimizer.run(filename, passes, listify(NODE_JS), jcache, debug, extra_info)
  File "/home/joel/emscripten/tools/js_optimizer.py", line 346, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info))
  File "/home/joel/emscripten/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/home/joel/emscripten/tools/js_optimizer.py", line 346, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info))
  File "/home/joel/emscripten/tools/js_optimizer.py", line 268, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
AssertionError: Error in js optimizer: 

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/tmp/tmpIE_SiY.jsfunc_8.js'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at read (/home/joel/emscripten/tools/js-optimizer.js:57:34)
    at Object.<anonymous> (/home/joel/emscripten/tools/js-optimizer.js:5200:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
joel@Discrete:~/freeimage-test$ 
/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
        throw new JS_Parse_Error(message, line, col, pos);
              ^
TypeError: object is not a function
    at new JS_Parse_Error (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
    at js_error (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
    at croak (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
    at token_error (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
    at expect_token (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:762:17)
    at Object.expect (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:765:40)
    at Object.1 (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1307:38)
    at prog1 (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
    at /home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1100:51
    at maybe_unary (/home/joel/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1209:27)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

I have tried this with nodejs, v8, and SpiderMonkey, and they all produce the same result. This is with the incoming branch of emscripten and llvm-3.2. My sample code, the library I'm using, and the saved bc from this run of em++ are available at https://drive.google.com/file/d/0B7QYgbtpmzDPMkRfNXJPdzJCT2M/edit?usp=sharing This seems to occur with any code that uses FreeImage and links this library.
