### ISSUE TITLE
2.0.17 on macOS : unexpected metadata key received from wasm-emscripten-finalize: globalImports

### ISSUE THREAD

**Issue by seyhajin** [emscripten-core/emscripten#13943]
Since i have upgraded to latest version of emscripten (2.0.16 -> 2.0.17) with Homebrew, i got this error message when i compile my usual sample C program :
```
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/usr/local/Cellar/emscripten/2.0.17/libexec/cache/generated_struct_info.json" for subsequent builds)
emcc: error: unexpected metadata key received from wasm-emscripten-finalize: globalImports
FAIL: Compilation failed!: ['/usr/local/Cellar/emscripten/2.0.17/libexec/emcc', '-D_GNU_SOURCE', '-o', '/var/folders/8b/6pbtc6_517l1h3k6vzng2x0m0000gn/T/tmpd2qd3v__.js', '/var/folders/8b/6pbtc6_517l1h3k6vzng2x0m0000gn/T/tmpxkhmm2iz.c', '-O0', '-Werror', '-Wno-format', '-nostdlib', '/usr/local/Cellar/emscripten/2.0.17/libexec/cache/sysroot/lib/wasm32-emscripten/libcompiler_rt.a', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'STRICT', '-s', 'SINGLE_FILE', '-Wno-error=version-check', '-Wno-deprecated']
```
my command line :
```
em++ -s FETCH=1 -s TOTAL_MEMORY=268435456 -s DISABLE_EXCEPTION_CATCHING=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0  -s WASM=1 -O3 -DNDEBUG=1 -s ASYNCIFY -s FORCE_FILESYSTEM=1 -s USE_GLFW=3 --shell-file [...]/shell.html -o [...]/entity-system.html [...]/entity.c.o "[...]/raylib.a"
```
*[...] replace full path*

It worked fine on version 2.0.16.
I'm on macOS Big Sur. 

Anyone known about it ?

**Comment by sbc100** [comment]
This happens then the version of binaryen doesn't match the version of emscripten.    Does homebrew use some external/independent version of binaryen or an emscripten-specific version (that later is really the only way to avoid these kind of issues)?

**Comment by seyhajin** [comment]
Yes, Homebrew had to install an external/independent version of binaryen

`brew info emscripten`
```
[21/04/21 12:43:09]  ~  brew info emscripten
emscripten: stable 2.0.17 (bottled), HEAD
LLVM bytecode to JavaScript compiler
https://emscripten.org/
/usr/local/Cellar/emscripten/2.0.17 (15,749 files, 1.1GB) *
  Poured from bottle on 2021-04-20 at 23:51:45
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/emscripten.rb
License: Apache-2.0 and (Apache-2.0 with LLVM-exception) and (MIT or NCSA)
==> Dependencies
Build: cmake ✔
Required: node ✔, python@3.9 ✔, yuicompressor ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 2,891 (30 days), 7,419 (90 days), 23,381 (365 days)
install-on-request: 2,269 (30 days), 5,589 (90 days), 19,064 (365 days)
build-error: 0 (30 days)
```

`brew info binaryen`
```
[21/04/21 12:43:34]  ~  brew info binaryen  
binaryen: stable 101 (bottled), HEAD
Compiler infrastructure and toolchain library for WebAssembly
https://webassembly.org/
/usr/local/Cellar/binaryen/101 (1,453 files, 39MB) *
  Poured from bottle on 2021-04-19 at 12:28:40
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/binaryen.rb
License: Apache-2.0
==> Dependencies
Build: cmake ✔, python@3.9 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 977 (30 days), 2,768 (90 days), 15,432 (365 days)
install-on-request: 427 (30 days), 1,104 (90 days), 4,725 (365 days)
build-error: 0 (30 days)
```

I will try to uninstall binaryen.

**Comment by seyhajin** [comment]
Thanks for informations.
I will use emsdk install instead of Homebrew.
