### ISSUE TITLE
Split JS file by some criterion

### ISSUE THREAD

**Issue by idini** [emscripten-core/emscripten#3294]
HI all.
I explain my situation ..
I have a project where different cpp files working on the same object pointed to memory. These sources need to import other classes from other sources in order to work, and those who import sources are common. If I import different generated files, the result, of course, is to have a multi-linking to specific functions and then runtime error.
If I build everything by generating a single JS file, file loading is slow because it is too large.
I would like to have different files JS, if possible according to class or module, so as to recall them at the appropriate time asynchronously.
I know that there was a flag "split" but that is deprecated. Are there other solutions?

**Comment by PaulAustin** [comment]
I have the same request, and had just started looking at options, one was a post processing step that breaks the larger JS file into smaller ones based on sets defined by exported symbols, though a more built-in system would be even better.

**Comment by idini** [comment]
Well.. If this is the only solution i would Try!  Have You a link or more
precisely documentation?
Il 30/mar/2015 23:59 "Paul Austin" <notifications@github.com> ha scritto:

**Comment by kripken** [comment]
emscripten used to have options related to that, but they had limitations and issues, and are deprecated. In current emscripten, we always emit all the code inside a single function scope (asm module).

The real question though is why is startup slow? Is it parsing, or compilation? How are you measuring it?

There are ways to improve startup speed, like outlining and the [emterpreter](https://github.com/kripken/emscripten/wiki/Emterpreter), but if they are helpful depends on the cause of the problem.

**Comment by idini** [comment]
The problem of slow loading is caused by the fact that I have many many features in my webapp, each specified by a cpp class, and this is a compilation problem, because each file, without optimization, has 5 MB size. I'd like to divide these functions and call asynchronously when I need, without being forced to call the entire block.

**Comment by kripken** [comment]
Does the code need to execute quickly? If not, interpreting it all will be fast to start up.

Do the codebases need to call each other? Perhaps they could each be compiled with their own heap, if not.

**Comment by idini** [comment]
the code needs to be loaded and executed quickly because it works with the
rendering. to the heap, you have an example?

**Comment by cignoni** [comment]
I am working with **idini** on the same project. Probably I can try to better clarify the issue. 
The objective is, more or less, to replicate classical plugin-based architectures. The idea is that we have a complex application where many functionality are implemented by plugins that are loaded on demand when they are needed. The advantages of this approach is mostly to delay the loading of not immediately needed code to the moment the user really needs it and to keep compilation of the various sub-parts as separate as possible.

**Comment by idini** [comment]
Thanks cignoni. I try to clarify with an example:
We have a class ```common.h``` with an object, a string.

```
class Common
{
    public:
    std::string str;
    void init() { str="pippo";}
};
```

and two classes, ```test1.cpp``` 
```
#include <stdlib.h>
#include <emscripten.h>
#include <emscripten/bind.h>
#include "common.h"

using namespace std;
using namespace emscripten;


class Test1 {

public:  
Test1(){}
  int generate1(){
    printf("generate");
      return 1;
  }
  
};

//Binding code
EMSCRIPTEN_BINDINGS(Test1) {
  class_<Test1>("Test1")
    .constructor<>()
    .function("generate1", &Test1::generate1)
    ;
}
```
and ```test2.cpp```

```
#include <stdlib.h>
#include <emscripten.h>
#include <emscripten/bind.h>
#include "common.h"

using namespace std;
using namespace emscripten;


class Test2 {

public:  
    int ppp;
Test2(){}
  int generate2(){
    printf("generate");
      return 2;
  }
  
};

//Binding code
EMSCRIPTEN_BINDINGS(Test2) {
  class_<Test2>("Test2")
    .constructor<>()
    .function("generate2", &Test2::generate2)
    ;
}
```


The two classes can be called in Javascript ONLY if they are compiled in an unique generated file.

If i compile separately, emcc compile, but one of them result "undefined" in JS runtime.

Moreover, object str of a class ```common.h``` is unaccessible. If I make accessible class Common with EMSCRIPTEN_BINDINGS, obviously the compiler report errors of type "symbol multiply defined", because "common.h" is inherited from both

**Comment by kripken** [comment]
I don't follow that. What commands do you run on those 2 files? How do you test them (in response to what is that `undefined` showing up)?

**Comment by idini** [comment]
I compile with 
```
emcc --bind -s DEMANGLE_SUPPORT=1  test2.cpp  -s TOTAL_MEMORY=268435456  -o test1.js
emcc --bind -s DEMANGLE_SUPPORT=1 test1.cpp -s TOTAL_MEMORY=268435456  -o test2.js
```
In JS call it with

```
var com = new Module.Common();
var t2 = new Module.Test2(); 
console.log(t2.generate2());            
var t1 = new Module.Test1();
console.log(t1.generate1());
```

the ```Uncaught TypeError: undefined is not a function```  correspond to the line 4, i.e ```var t1 = new Module.Test1();```. If i compile test1.cpp first to test2.cpp then error correspond to line 2, i.e ```var t2 = new Module.Test2(); ```.
Also ```var com = new Module.Common();``` of class ```common.h``` is undefined, i think because it isn't binded.

If I execute code of Test1 and Test2, I must compile with 
```emcc --bind  test 1.cpp test2.cpp  -o test.js```

**Comment by kripken** [comment]
And do you just include `test1.js, test2.js` as script tags? They are both on the same global scope then, and the second one is overwriting global stuff from the first. You can use MODULARIZE to wrap them in functions, to keep them entirely separate.

**Comment by idini** [comment]
Ok thanks, i updated emscripten. Version is 1.30.
I was looking for documentation about Modularize, but anything.
Compile is ok, by 
 ```
emcc --bind -s MODULARIZE=1 test2.cpp -o test2.js
emcc --bind -s MODULARIZE=1 test1.cpp -o test1.js
```

but now it's all undefined.
Missing some flags?

Thank you very much

**Comment by kripken** [comment]
Not sure. Might be an embind problem. cc @chadaustin

**Comment by chadaustin** [comment]
I don't have enough context here to know what could be going on.

I don't believe embind currently supports separate compilation of .js "executables" and then dynamically connecting them at runtime.  It assumes everything's in the same address space.

**Comment by waywardmonkeys** [comment]
I suspect the new dynamic linking support might work here for this use case?

**Comment by pplcf** [comment]
This is a big issue for a large projects since browser HTTP cache limits the file size to ~4-5mb(varies a little bit for different platforms/browsers), so every time page is refreshed it has to download almost whole app again. LocalStorage is also limited to 5mb, HTML5 AppManifest is deprecated, Service Workers are still experimental, IndexedDB is buggy and not reliable across browsers and WebSQL is webkit only. The only way to achieve good crossbrowser resource caching without 3rd party libs is to use in-browser HTTP cache.
