### ISSUE TITLE
Compile failure around std::shared_ptr<X> indirection in 3.1.66, while same code worked previously

### ISSUE THREAD

**Issue by carlopi** [emscripten-core/emscripten#22573]
Code is something like this:
```c++
struct ArrayData {
    /*     more code */
    int64_t offset = 0;
};

struct Wrapper {
    /*     more code */
    std::shared_ptr<ArrayData> data_;
};

struct WrapperInherited {
    /*     more code */
    int64_t someFun() {
         return data_->offset;
    }
}
```
And it does compile correctly in `3.1.65` (and any of the last 10+ versions) while it's throws a compiler error like:
```
/Users/carlo/duckdb-wasm/submodules/arrow/cpp/src/arrow/array/array_binary.h:61:17: error: no member named 'offset' in 'std::shared_ptr<arrow::ArrayData>'
```
in 3.1.66.

Note that changing the code to:
```c++
struct WrapperInherited {
    /*     more code */
    int64_t someFun() {
         return (*data_).offset;
    }
}
```
make also 3.1.66 compile successfully.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.66 (1f519517284660f4b31ef9b7f921bf6ba66c4041)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 7543d09b852695187d08aa5d56d50016fea8f706)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/carlo/emsdk/upstream/bin
```

**Failing command line in full:**
```
In file included from /Users/carlo/duckdb-wasm/submodules/arrow/cpp/src/arrow/compute/exec.cc:29:
/Users/carlo/duckdb-wasm/submodules/arrow/cpp/src/arrow/array/array_primitive.h:106:70: error: no member named 'offset' in 'std::shared_ptr<arrow::ArrayData>'
  106 |     return reinterpret_cast<const value_type*>(raw_values_) + data_->offset;
      |                                                               ~~~~~  ^
In file included from /Users/carlo/duckdb-wasm/submodules/arrow/cpp/src/arrow/compute/exec.cc:34:
In file included from /Users/carlo/duckdb-wasm/submodules/arrow/cpp/src/arrow/compute/exec_internal.h:26:
In file included from /Users/carlo/duckdb-wasm/submodules/arrow/cpp/src/arrow/array.h:44:
/Users/carlo/duckdb-wasm/submodules/arrow/cpp/src/arrow/array/array_binary.h:61:17: error: no member named 'offset' in 'std::shared_ptr<arrow::ArrayData>'
   61 |     i += data_->offset;
      |          ~~~~~  ^
```

**Full link command and output with `-v` appended:**
```
+ emcmake cmake -S/Users/carlo/duckdb-wasm/lib -B/Users/carlo/duckdb-wasm/build/relsize/eh -DDUCKDB_WASM_VERSION=unknown -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DDUCKDB_LOCATION=/Users/carlo/duckdb-wasm/submodules/duckdb -DWASM_LINK_FLAGS_EXT= -DDUCKDB_EXTENSION_CONFIGS=extension_config_wasm.cmake -DCMAKE_BUILD_TYPE=Release -DWASM_MIN_SIZE=1 -DWITH_WASM_EXCEPTIONS=1 -DDUCKDB_CUSTOM_PLATFORM=wasm_eh -DDUCKDB_EXPLICIT_PLATFORM=wasm_eh
configure: cmake -S/Users/carlo/duckdb-wasm/lib -B/Users/carlo/duckdb-wasm/build/relsize/eh -DDUCKDB_WASM_VERSION=unknown -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DDUCKDB_LOCATION=/Users/carlo/duckdb-wasm/submodules/duckdb -DWASM_LINK_FLAGS_EXT= -DDUCKDB_EXTENSION_CONFIGS=extension_config_wasm.cmake -DCMAKE_BUILD_TYPE=Release -DWASM_MIN_SIZE=1 -DWITH_WASM_EXCEPTIONS=1 -DDUCKDB_CUSTOM_PLATFORM=wasm_eh -DDUCKDB_EXPLICIT_PLATFORM=wasm_eh -DCMAKE_TOOLCHAIN_FILE=/Users/carlo/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/carlo/emsdk/node/16.20.0_64bit/bin/node
CMake Warning (dev) at CMakeLists.txt:6 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- EMSDK=/Users/carlo/emsdk
-- CCACHE_PROGRAM=/opt/homebrew/bin/ccache
DUCKDB_CXX_FLAGS= -std=c++17 -DDUCKDB_WASM=1 -DFSST_MUST_ALIGN -DWASM_LOADABLE_EXTENSIONS=1 -DDUCKDB_EXTENSION_AUTOLOAD_DEFAULT=1 -fPIC -DNDEBUG -fwasm-exceptions -DWEBDB_FAST_EXCEPTIONS=1 -sUSE_PTHREADS=0 -DDUCKDB_NO_THREADS=1 -sUSE_PTHREADS=0 -DDUCKDB_NO_THREADS=1 -DDUCKDB_CUSTOM_PLATFORM=wasm_eh -Wno-unqualified-std-cast-call -DDUCKDB_DEBUG_NO_SAFETY -DDUCKDB_FROM_DUCKDB_WASM
-- WASM_LINK_FLAGS= -Oz -sUSE_PTHREADS=0 -s MAIN_MODULE=1 -s FILESYSTEM=1 -s ENVIRONMENT='web,node,worker' -s ALLOW_TABLE_GROWTH -lembind
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/carlo/duckdb-wasm/build/relsize/eh
+ emmake make -C/Users/carlo/duckdb-wasm/build/relsize/eh -j8 duckdb_wasm
make: make -C/Users/carlo/duckdb-wasm/build/relsize/eh -j8 duckdb_wasm
```

**More context:**
This happened while compiling [duckdb-wasm](https://github.com/duckdb/duckdb-wasm), that has uses [apache/arrow](https://github.com/apache/arrow) as subcomponent, so it's not really handy to modify the code (although as a workaround I imagine I will have to).

Extracting a reproduction is not obvious, but maybe if someone can point to me to the right direction I might be able to help.

**Comment by brendandahl** [comment]
This is a bug in the LLVM version that was released with 3.1.66. We're rolling out a new release to address it.

**Comment by carlopi** [comment]
Great, and thanks for the answer

**Comment by brendandahl** [comment]
3.1.67 is out. Closing the issue, but leave a comment if you're still having issues with the new version.

**Comment by carlopi** [comment]
Thanks!
