### ISSUE TITLE
Can't build GNU diffutils with emscripten

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#12879]
Getting really strange errors on Emscripten 2.0.5:
```
In file included from /mnt/c/Users/user/busyide/source/diffutils/lib/bitrotate.c:3:
/mnt/c/Users/user/busyide/source/diffutils/lib/bitrotate.h:78:60: error: expected expression
  return ((x << n) | (x >> ((CHAR_BIT * sizeof x) - n))) & SIZE_MAX;
                                                           ^
./stdint.h:558:21: note: expanded from macro 'SIZE_MAX'
#  define SIZE_MAX  _STDINT_MAX (0, , 0ul)
                    ^
./stdint.h:141:30: note: expanded from macro '_STDINT_MAX'
    (((((zero) + 1) << ((bits) ? (bits) - 1 - (signed) : 0)) - 1) * 2 + 1)
                             ^
In file included from /mnt/c/Users/user/busyide/source/diffutils/lib/bitrotate.c:3:
/mnt/c/Users/user/busyide/source/diffutils/lib/bitrotate.h:78:60: error: expected expression
./stdint.h:558:21: note: expanded from macro 'SIZE_MAX'
#  define SIZE_MAX  _STDINT_MAX (0, , 0ul)
                    ^
./stdint.h:141:39: note: expanded from macro '_STDINT_MAX'
    (((((zero) + 1) << ((bits) ? (bits) - 1 - (signed) : 0)) - 1) * 2 + 1)
In file included from /mnt/c/Users/user/busyide/source/diffutils/lib/bitrotate.c:3:
/mnt/c/Users/user/busyide/source/diffutils/lib/bitrotate.h:87:60: error: expected expression
./stdint.h:558:21: note: expanded from macro 'SIZE_MAX'
#  define SIZE_MAX  _STDINT_MAX (0, , 0ul)
                    ^
./stdint.h:141:39: note: expanded from macro '_STDINT_MAX'
    (((((zero) + 1) << ((bits) ? (bits) - 1 - (signed) : 0)) - 1) * 2 + 1)
                                      ^
                                      ^
4 errors generated.
emcc: error: '/mnt/c/Users/user/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=5 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/include -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/include/SSE -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/include/neon -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/lib/compiler-rt/include -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/lib/libunwind/include -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/cache/wasm/include -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -I. -I/mnt/c/Users/user/busyide/source/diffutils/lib -Oz -MT bitrotate.o -MD -MP -MF .deps/bitrotate.Tpo -c -o bitrotate.o /mnt/c/Users/user/busyide/source/diffutils/lib/bitrotate.c -Xclang -isystem/mnt/c/Users/user/emsdk/upstream/emscripten/system/include/SDL -c -o bitrotate.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
Makefile:1924: recipe for target 'bitrotate.o' failed
make[2]: *** [bitrotate.o] Error 1
make[2]: Leaving directory '/mnt/c/Users/user/busyide/build/wasm/diffutils/lib'
Makefile:1678: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/mnt/c/Users/user/busyide/build/wasm/diffutils/lib'
Makefile:1361: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
make: make
```

Full repro script:
```shell
set -e

ROOT=$PWD
CONFIGURE_wasm="emconfigure"
MAKE_wasm="emmake make"

URL_diffutils=https://ftp.gnu.org/gnu/diffutils/diffutils-3.7.tar.xz
CFLAGS_wasm_diffutils='-s ERROR_ON_UNDEFINED_SYMBOLS=0 -lidbfs.js -s WASM=1 -s SINGLE_FILE=1 -s MODULARIZE=1 -s EXPORT_NAME=busy -s FORCE_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=[\"FS\"] -s INVOKE_RUN=0 -Oz'
CACHE_wasm_diffutils=$ROOT/build/wasm-diffutils.cache

mkdir -p source/diffutils build/wasm/diffutils
wget --no-clobber $URL_diffutils -O source/$(basename $URL_diffutils)
tar -xf source/$(basename $URL_diffutils) --strip-components=1 --directory=source/diffutils

printf "ac_cv_search_nanosleep=yes\ngl_cv_func_nanosleep=no\ngl_cv_func_sleep_works=yes" > $ROOT/config.site

pushd build/wasm/diffutils
CONFIG_SITE=$ROOT/diffutils.site ${CONFIGURE_wasm} $ROOT/source/diffutils/configure --cache-file=${CACHE_wasm_diffutils} CFLAGS="${CFLAGS_wasm_diffutils}"
${MAKE_wasm}
popd
```

Log of configure step: [configure.txt](https://github.com/emscripten-core/emscripten/files/5593065/configure.txt)
Log of make step: [make.txt](https://github.com/emscripten-core/emscripten/files/5593067/make.txt)

**Comment by vadimkantorov** [comment]
I'm doing the build on WSLv1 on Ubuntu 18.04 on a case-insensitive mount. I'm worried that GNU diffutils somehow discovered I'm using Windows and tried to do some nasty things because of it. After manually patching the config.site I stumbled on this error:
```
                                                                                                                                  127,1         Bot
emcc: warning: argument unused during compilation: '-lidbfs.js' [-Wunused-command-line-argument]
  CC       msvc-inval.o
/mnt/c/Users/user/busyide/source/diffutils/lib/msvc-inval.c:124:7: error: implicit declaration of function '_set_invalid_parameter_handler' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      _set_invalid_parameter_handler (gl_msvc_invalid_parameter_handler);
      ^
/mnt/c/Users/user/busyide/source/diffutils/lib/msvc-inval.c:124:7: note: did you mean 'gl_msvc_invalid_parameter_handler'?
/mnt/c/Users/user/busyide/source/diffutils/lib/msvc-inval.c:32:1: note: 'gl_msvc_invalid_parameter_handler' declared here
gl_msvc_invalid_parameter_handler (const wchar_t *expression,
^
1 error generated.
```

**Comment by vadimkantorov** [comment]
These problems seem to repro on GitHub Actions. This is the config.site that I had to use to build it with Emscripten:
```
ac_cv_search_nanosleep=yes
gl_cv_func_nanosleep=no
gl_cv_func_sleep_works=yes
ac_cv_func_getprogname=no
ac_cv_func_wmempcpy=no
ac_cv_func_rawmemchr=no
ac_cv_func__set_invalid_parameter_handler=no
ac_cv_func_strcasecoll=no
ac_cv_func_stricoll=no
gl_cv_bitsizeof_ptrdiff_t=32
gl_cv_bitsizeof_sig_atomic_t=32
gl_cv_bitsizeof_size_t=32
gl_cv_bitsizeof_wchar_t=16
gl_cv_bitsizeof_wint_t=32
```

To sum up, Emscripten build can't detect absence of some functions and the sizeof of size_t types.

**Comment by sbc100** [comment]
If you'd like to improve our support for autoconf help would be much appreciated.  We do some basic tests but clearly there are things we could improve.

One area I'd like to revisit is whether we should pretend to be a native compiler or not.  I think today we pretend that we are native copiler with executable that can run the build host.. I think maybe we should be honest and admit to autoconf that we are a cross compiler.

**Comment by vadimkantorov** [comment]
I think these checks are executed fine during configure time. A question is why these functions link successfully during checks and do not link at actual compile-time?

**Comment by vadimkantorov** [comment]
Also, if I'm not mistaken, a few versions of Emscripten earlier just sleep hacks were needed.

**Comment by sbc100** [comment]
I'm not sure what you mean by "do not link at actual compile-time".. the errors above look like compile error no link errors.  

I'm also not sure that you mean by "just sleep hacks were needed.".    Are you saying things used to work and they don't?  What sleep hacks are your referring too?   

If there was a specific regression it would be great to know exactly which emscripten revision caused it.

**Comment by vadimkantorov** [comment]
1. I meant that autoconf checks seem to pass compilation successfully. And compilation fails at the "make" step.

2. Yep, I think previously only the following were needed.
```
ac_cv_search_nanosleep=yes
gl_cv_func_nanosleep=no
gl_cv_func_sleep_works=yes
```

3. I'll try to find the old version where it worked with only sleep hacks, and will let you know

**Comment by sbc100** [comment]
BTW, hopefully you won't need the sleep at anymore as of a recent change : https://github.com/emscripten-core/emscripten/pull/12872

**Comment by vadimkantorov** [comment]
The sleep hacks were becasue of unsupported `alarm()` emulation...
