### ISSUE TITLE
[question] New clang error after upgrade to 2.0.24 from 2.0.4

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#14661]
I've added `-Wno-unused-variable -Wno-unused-but-set-variable` to my emcc flags, but it hasn't helped. I realise it's maybe more of clang question, but maybe I'm missing something.

```
/home/runner/work/busytex/busytex/source/texlive/libs/harfbuzz/harfbuzz-src/src/hb-subset-cff1.cc:405:33: error: variable 'supp_size' set but not used [-Werror,-Wunused-but-set-variable]
8157
    unsigned int  size0, size1, supp_size;
8158
                                ^
8159
1 error generated.
8160
em++: error: '/home/runner/work/_temp/ca142886-c622-4376-b2d1-960c015c4935/emsdk-main/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=24 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/home/runner/work/_temp/ca142886-c622-4376-b2d1-960c015c4935/emsdk-main/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DHAVE_CONFIG_H -I. -I/home/runner/work/busytex/busytex/source/texlive/libs/harfbuzz -DHB_NO_MT -DHAVE_FALLBACK=1 -I/home/runner/work/busytex/busytex/source/texlive/libs/harfbuzz/harfbuzz-src/src -I/home/runner/work/busytex/busytex/build/wasm/texlive/libs/graphite2/include -DGRAPHITE2_STATIC -I/home/runner/work/busytex/busytex/build/wasm/texlive/libs/icu/include -I/home/runner/work/busytex/busytex/source/fontconfig -Oz -Wno-unused-variable -Wno-unused-but-set-variable -Wreturn-type -Wno-write-strings -I/home/runner/work/busytex/busytex/build/wasm/texlive/libs/icu/include -I/home/runner/work/busytex/busytex/source/fontconfig -Oz -Wno-unused-variable -Wno-unused-but-set-variable -fno-rtti -fno-exceptions -Wcast-align -MT harfbuzz-src/src/hb-subset-cff1.o -MD -MP -MF harfbuzz-src/src/.deps/hb-subset-cff1.Tpo -c /home/runner/work/busytex/busytex/source/texlive/libs/harfbuzz/harfbuzz-src/src/hb-subset-cff1.cc -o harfbuzz-src/src/hb-subset-cff1.o' failed (returned 1)
```

**Comment by vadimkantorov** [comment]
I've also tried adding `-Wno-error=unused-but-set-variable` to no avail (it's present in the compilation line, but it still fails)

**Comment by sbc100** [comment]
Seems very odd.   Are you able to reproduce with a simple or shareable example?   It could be that this is an upstream clang issue.

**Comment by vadimkantorov** [comment]
I do have a repro, but it takes more than 1h to run on GitHub Workflows (it's compiling TexLive with Emscripten). I can also try to find the emsdk version which starts failing.

**Comment by kripken** [comment]
One hour makes it harder than usual, but still I think bisection is the best approach here. You'd at least only have a logarithmic number of those 1-hour steps - can probably finish it in one or two days.

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by sbc100** [comment]
If its just a compile error you should simple be able to run the single failing emcc command (no need to run the entire build), and then you can also run it with `-E` and attach the pre-processed source here.

**Comment by vadimkantorov** [comment]
A problem is that I build this on GitHub Workflow, and instrumenting this for me is not easy :(

Locally the build takes even longer - I'll do it when I find the offending emsdk version. 2.0.10 worked fine. Now trying 2.0.15

**Comment by vadimkantorov** [comment]
Also, it seems that Emscripten 2.0.26 is released on July 2, but emsdk 2.0.26 is still unavailable

**Comment by sbc100** [comment]
What makes you think 2.0.26 has been released?  As far as I can tell we are still on 2.0.25: https://github.com/emscripten-core/emscripten/tags

**Comment by vadimkantorov** [comment]
![image](https://user-images.githubusercontent.com/1041752/126599954-2118ae12-bb2b-4249-a8be-7c857bccc946.png)

**Comment by vadimkantorov** [comment]
2.0.23 is fine, 2.0.24 and 2.0.25 are producing the compilation error

**Comment by vadimkantorov** [comment]
Unfortunately, 2.0.23 produces these errors under Safari:
```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'Module["asm"]["oa"]')
	receiveInstance (busybox_unstripped.js:9:10785)
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'Module['asm']['memory']')
	receiveInstance (busytex.js:1734)
	promiseReactionJob
```
so can't use it either.

**Comment by vadimkantorov** [comment]
I'll try to get compilation failing/working locally under 2.0.25

**Comment by sbc100** [comment]
Ah, that looks like a bug in our documentation site building: https://github.com/emscripten-core/emscripten/issues/14726

**Comment by vadimkantorov** [comment]
It even mentions release date and proposes to read the changelog :)

**Comment by sbc100** [comment]
The reason is that the ChangeLog and version stored in git includes the not-yet-released upcoming version.

**Comment by vadimkantorov** [comment]
So two problems left:
1. figuring out why Emscripten / clang fails on versions 2.0.24+
2. figuring out why 2.0.23 fails on Safari and whether 2.0.24+ would fail with the same error...

**Comment by vadimkantorov** [comment]
Should I file a separate issue about the Safari errors? Or are they known fixed bugs?

**Comment by kleisauke** [comment]
Could you try to update HarfBuzz to 2.8.2? That error should be fixed with commit https://github.com/harfbuzz/harfbuzz/commit/243d056ff1c2af583ceb67e5dfbfaac51dc96e63. The reason it could not be disabled via the command line is because of this `#pragma GCC diagnostic error` directive:
https://github.com/harfbuzz/harfbuzz/blob/3e4f006fe24186182b12ec04776aedbc0f6659b3/src/hb.hh#L89

(The `-Wunused-but-set-parameter` and `-Wunused-but-set-variable` warnings were landed in LLVM with commit https://github.com/llvm/llvm-project/commit/cf49cae278b4e972cd2547d72f9ee7d9d69a3af4)

**Comment by vadimkantorov** [comment]
About harfbuzz: that's what I'm trying

About clang: why hasn't -Wno-error=unused-but-set-variable hasn't helped to suppress the error? Is it because the pragmas in harfbufzz overrode it somehow?

**Comment by kleisauke** [comment]
Indeed, those `#pragma GCC diagnostic` directives will override any command-line options. Alternatively, you could also define `HB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR` (e.g. via the command line with `-DHB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR`).

**Comment by vadimkantorov** [comment]
Interesting. Case solved I guess :)

About Safari I created a new issue: https://github.com/emscripten-core/emscripten/issues/14777
