### ISSUE TITLE
 SDL2_mixer fails on Windows even with 1.39.4

### ISSUE THREAD

**Issue by mrj0721** [emscripten-core/emscripten#9961]
Compared to 1.39.3, error messages are certainly reduced.
But it still doesn't compile.

<pre>
root:INFO: building port: sdl2_mixer
Traceback (most recent call last):
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 3704, in <module>
    sys.exit(run(sys.argv))
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 1960, in run
    compile_source_file(i, input_file)
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 1942, in compile_source_file
    cmd = get_clang_command([input_file]) + ['-c', '-o', output_file]
  File "C:\Program Files\emsdk\upstream\emscripten\emcc.py", line 1913, in get_clang_command
    args = system_libs.process_args(args, shared.Settings)
  File "C:\Program Files\emsdk\upstream\emscripten\tools\system_libs.py", line 1762, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "C:\Program Files\emsdk\upstream\emscripten\tools\ports\sdl2_mixer.py", line 57, in process_args
    get(ports, settings, shared)
  File "C:\Program Files\emsdk\upstream\emscripten\tools\ports\sdl2_mixer.py", line 42, in get
    return [shared.Cache.get(libname, create, what='port')]
  File "C:\Program Files\emsdk\upstream\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "C:\Program Files\emsdk\upstream\emscripten\tools\ports\sdl2_mixer.py", line 32, in create
    os.symlink(dest_path, os.path.join(dest_path, 'SDL2'))
AttributeError: 'module' object has no attribute 'symlink'
make: *** [main.o] Error 1
</pre>

by Windows10

**Comment by kripken** [comment]
Thanks @mrj0721 , looks like https://github.com/emscripten-core/emscripten/issues/9933 didn't fix this completely, then.

[The docs](https://docs.python.org/3/library/os.html#os.symlink) suggest `os.symlink` should be present on windows, though - what version of python are you using?

**Comment by sbc100** [comment]
I don't think windows generally supports symbol links.    We should probably not depend on them. 

@Oipo can you take a look?    Looks like this was introduced in #9849.  Sorry i didn't catch it at the time.  Still its closer to working on windows that before :)

**Comment by mrj0721** [comment]
> Thanks @mrj0721 , looks like #9933 didn't fix this completely, then.
> 
> [The docs](https://docs.python.org/3/library/os.html#os.symlink) suggest `os.symlink` should be present on windows, though - what version of python are you using?

python-2.7.13.1-64bit

**Comment by Oipo** [comment]
The [python docs for v2.7](https://docs.python.org/2.7/library/os.html#os.symlink) suggest that it is not available for windows. Selecting version 3.5 of the docs shows that somewhere between 2.7 and 3.5, windows support has been added. 

If emscripten wants to continue to support the [deprecated version 2.7](https://www.python.org/dev/peps/pep-0373/) past its duedate in 2020, that'll be a big burden. My suggestion is to make python 3.5 or later a hard requirement instead.

**Comment by sbc100** [comment]
Sorry, that we can do easily right now.   Even with 3.5 I think symlinks work well on windows in general. 
 I think its best we don't depend on symbols for now.  Sorry.

**Comment by Oipo** [comment]
I disagree with that notion. I managed to track down when it was actually implemented: [2010](https://bugs.python.org/issue1578269), version 3.2. Vista and up have proper support for symlinks.

Regardless, I started a new job this week and won't be having time for this until after Christmas.
