### ISSUE TITLE
problem with glTexStorage3D

### ISSUE THREAD

**Issue by MaxPowerton** [emscripten-core/emscripten#10479]
Hi guys,

after updating from 1.37.26 to the current latest, my app broke and i cannot get it working again.
I completely removed emscripten including all caches and reinstalled the latest.
One of the issues is following exception:

exception thrown: TypeError: GLctx.texStorage3D is not a function,TypeError: GLctx.texStorage3D is not a function
    at _glTexStorage3D (http://localhost:6931/test.js:3482:75)

I made a somewhat minimal reproducible example by modifying the Simple_Texture2D.c example to use WEBGL2 and glTexStorage3D
[glTexStorage3Dtest.zip](https://github.com/emscripten-core/emscripten/files/4209612/glTexStorage3Dtest.zip)

only changes are:

in esUtil.h:

#ifdef OLD_CODE
#include <GLES2/gl2.h>
#else
#include <GLES3/gl32.h>
#endif
#include <EGL/egl.h>

in Simple_Texture2D.c:

#ifdef OLD_CODE
   glTexImage2D ( GL_TEXTURE_2D, 0, GL_RGB, 2, 2, 0, GL_RGB, GL_UNSIGNED_BYTE, pixels );
#else
	glTexStorage3D(GL_TEXTURE_2D_ARRAY, 0, GL_RGB, 2, 2, 1);
	glTexSubImage3D(GL_TEXTURE_2D_ARRAY, 0, 0, 0, 0, 2, 2, 1, GL_RGB, GL_UNSIGNED_BYTE, pixels);
#endif

build script is included as well.

toggle the "#define OLD_CODE" in  esUtil.h to switch between old / new

any help would be appreciated.

Thanks!

and this is my installation:

The *recommended* precompiled SDK download is 1.39.8 (9e60f34accb4627d7358223862a7e74291886ab6).

To install/activate it, use one of:
         latest                  [default (llvm) backend]
         latest-fastcomp         [legacy (fastcomp) backend]

Those are equivalent to installing/activating the following:
         1.39.8
         1.39.8-fastcomp

All recent (non-legacy) installable versions are:
         1.39.8
         1.39.7
         1.39.6
         1.39.5
         1.39.4
         1.39.3
         1.39.2
         1.39.1
         1.39.0
         1.38.48
         1.38.47
         1.38.46
         1.38.45
         1.38.44
         1.38.43
         1.38.42
         1.38.41
         1.38.40
         1.38.39
         1.38.38
         1.38.37
         1.38.36
         1.38.35
         1.38.34
         1.38.33

The additional following precompiled SDKs are also available for download:
Manifest error: No tool by name 'clang-e1.37.1-64bit' found! This may indicate an internal SDK error!
Manifest error: No tool by name 'clang-e1.37.1-64bit' found! This may indicate an internal SDK error!
         sdk-1.37.1-64bit
    *    sdk-releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit   INSTALLED
    *    sdk-releases-upstream-99e2c36ac5c45042a786119919aedacf342e8b53-64bit   INSTALLED
         sdk-releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit
         sdk-releases-fastcomp-99e2c36ac5c45042a786119919aedacf342e8b53-64bit
         sdk-fastcomp-1.38.30-64bit
         sdk-fastcomp-1.38.31-64bit

The following SDKs can be compiled from source:
         sdk-upstream-master-64bit
         sdk-fastcomp-master-32bit
         sdk-fastcomp-master-64bit
         sdk-fastcomp-tag-1.38.30-64bit
         sdk-fastcomp-tag-1.38.31-64bit

The following precompiled tool packages are available for download:
    (*)    releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit     INSTALLED
    (*)    releases-upstream-99e2c36ac5c45042a786119919aedacf342e8b53-64bit     INSTALLED
           releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit
           releases-fastcomp-99e2c36ac5c45042a786119919aedacf342e8b53-64bit
           fastcomp-clang-e1.38.30-64bit
           fastcomp-clang-e1.38.31-64bit
           node-4.1.1-64bit
           node-8.9.1-64bit
    (*)    node-12.9.1-64bit            INSTALLED
           python-2.7.13.1-64bit
    (*)    python-3.7.4-64bit           INSTALLED
    (*)    java-8.152-64bit             INSTALLED
           emscripten-1.38.30
           emscripten-1.38.31
           gnu-2.5.4
           mingw-7.1.0-64bit

The following tools can be compiled from source:
           llvm-git-master-32bit
           llvm-git-master-64bit
           clang-tag-e1.38.30-32bit
           clang-tag-e1.38.31-32bit
           fastcomp-clang-tag-e1.38.30-64bit
           fastcomp-clang-tag-e1.38.31-64bit
           fastcomp-clang-master-32bit
           fastcomp-clang-master-64bit
           emscripten-tag-1.38.30-32bit
           emscripten-tag-1.38.31-32bit
           emscripten-tag-1.38.30-64bit
           emscripten-tag-1.38.31-64bit
           binaryen-tag-1.38.30-32bit
           binaryen-tag-1.38.31-32bit
           binaryen-tag-1.38.30-64bit
           binaryen-tag-1.38.31-64bit
           emscripten-master-32bit
           emscripten-master-64bit
           binaryen-master-32bit
           binaryen-master-64bit

**Comment by MaxPowerton** [comment]
Hi guys, was further looking into this today and found out i can make my app work again using this hack:

in the .js there is always following piece of code:

var ctx = 
          (webGLContextAttributes.majorVersion > 1)
          ?
            canvas.getContext("webgl2", webGLContextAttributes)
          :
          (canvas.getContext("webgl", webGLContextAttributes)
            // https://caniuse.com/#feat=webgl
            );

if i change the condition to always evaluate to true the app works again.
As far as why webGLContextAttributes.majorVersion is 1 instead of 2, that is because WebGL2RenderingContext is undefined.

So far i didnt quite understand why WebGL2RenderingContext is undefined now with the new version. Will continue try and figure this out at some point.

Kind Regards

**Comment by juj** [comment]
In the repro, in esUtil.c function `CreateEGLContext`, the code initializes a GLES2 (WebGL1) context:
```
   EGLint contextAttribs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE, EGL_NONE };
```
Changing that to initialize a GLES3 (WebGL 2) context with
```
   EGLint contextAttribs[] = { EGL_CONTEXT_CLIENT_VERSION, 3, EGL_NONE, EGL_NONE };
```
makes the test pass for me.

**Comment by MaxPowerton** [comment]
oh thanks a lot, i added
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
in my app which should have been there anyway i guess. now it works.

**Comment by MaxPowerton** [comment]
thanks for the help again, closing this
