### ISSUE TITLE
Since commit 5c6e163, OpenCV does not compile anymore

### ISSUE THREAD

**Issue by severin-lemaignan** [emscripten-core/emscripten#1857]
OpenCV master does not compile anymore with `emscripten`.

While it compiled fine with `emscripten 1.5.4`, it does not compile anymore with recent version.

Precisely, the compilation breaks here:
https://github.com/Itseez/opencv/blob/master/modules/core/src/system.cpp#L475 with this error: `error: use of undeclared identifier 'close'`

After running `git bisect`, it appears that the issue arose with this commit: 5c6e1633d218bd5b9c5077634829eb14d326308f

Any idea how to solve this?
