### ISSUE TITLE
Don't warn on BINARYEN_ASYNC_COMPILATION disabled due to user options in SIDE_MODULE

### ISSUE THREAD

**Issue by rrhitman** [emscripten-core/emscripten#6837]
Hello, 
I am new to emscripten. I have a module which is used as shared library and a main module which uses dlopen to open the shared library. However I use the following command to build the shared library.

`emcc -O1 -s BINARYEN_ASYNC_COMPILATION=1 -s SIDE_MODULE=1 testLib.cpp -o testLib.bc`

I following warning:

> WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects

I am using emscripten 1.38.8. What am I doing wrong here ?

I opened the same issue in Webassembly/binaryen

**Comment by kripken** [comment]
Thanks, we should remove that warning: A side module does not have any compilation code of its own, it is just pure wasm, and is loaded by the main file. So the warning is confusing and irrelevant. Renaming the issue for that.

Anyhow, you can ignore the warning for now - there are no harmful effects.

**Comment by rrhitman** [comment]
Hello,

Thanks for the reply. N also for providing the link. However, even after packaging the .bc file, I get an error when I run the html file as follows:
![image](https://user-images.githubusercontent.com/41010610/42638242-1af817dc-85bb-11e8-9c0a-5c390c49cf2a.png)

In the command line: I get these errors:

> Executing /usr/bin/xdg-open http://localhost:6931/test.html
Fontconfig warning: "/etc/fonts/fonts.conf", line 160: blank doesn't take any effect anymore. please remove it from your fonts.conf
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[4756:4756:0712/170431.698900:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
[4715:4715:0712/170431.783083:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
The html page you are running is not emrun-capable. Stdout, stderr and exit(returncode) capture will not work. Recompile the application with the --emrun linker flag to enable this, or pass --no_emrun_detect to emrun to hide this check.

I build my shared library as follows:
`emcc -O1 -std=c++11 -s BINARYEN_ASYNC_COMPILATION=1 -s SIDE_MODULE=1 testLib.cpp -o testLib.bc`

Then the main module as follows:
`emcc -O1 -std=c++11 -s BINARYEN_ASYNC_COMPILATION=1 -s MAIN_MODULE=1 -s WASM=1 main.cpp -o test.html --preload-file testLib.bc`

I am sure the code is not the problem as it is a simple printing output with dynamically linking the shared library and it worked in g++ and I got the output.

**Comment by rrhitman** [comment]
Just in case, here is the C++ code. 
testVir.h
`#ifndef TESTVIR_H
#define TESTVIR_H
 
class TestVir
{
public:
  virtual void init()=0;
  virtual ~TestVir() = default;
};
 
#endif`

testLib.h
`#ifndef TESTLIB_H
#define TESTLIB_H
 
class TestLib : public TestVir
{
 public:
     void init();
};
 
#endif`

testLib.cpp
`#include <iostream>
#include "testVir.h"
#include "testLib.h"
 
using namespace std;
void TestLib::init()
{
   cout<<"TestLib::init: Hello World!! "<<endl ;
}
 
//Define functions with C symbols (create/destroy TestLib instance).
extern "C" TestVir* create()
{
    return new TestLib();
}
extern "C" void destroy(TestVir* Tl)
{
   delete Tl ;
}`

main.cpp
`#include<iostream>
#include<dlfcn.h>
#include "testVir.h"
 
using namespace std;
 
int main()
{
    void *handle;
    handle = dlopen("./testLib.so", RTLD_NOW);
    if (!handle)
    {
           printf("The error is %s", dlerror());
           exit(0);
    }
 
    typedef TestVir* create_t();
    typedef void destroy_t(TestVir*);
 
    create_t* creat=(create_t*)dlsym(handle,"create");
    destroy_t* destroy=(destroy_t*)dlsym(handle,"destroy");
    if (!creat)
    {
           cout<<"The error is %s"<<dlerror();
           exit(0);
    }
    if (!destroy)
    {
           cout<<"The error is %s"<<dlerror();
           exit(0);
    }
    TestVir* tst = creat();
    tst->init();
    destroy(tst);
    return 0 ;
}`

**Comment by rrhitman** [comment]
Also, for General dynamic Linking it is mentioned that  I need to add the module in Module.dynamicLibraries. I have 2 questions.

Is this Module.dynamicLibraries an option in emcc which can be access by -s or is it something that I need to add in the code or create a new .js file with the module structure being initialized ? 

If it is the last two, then how to do that ? or can you point me to the link which explains that ?

**Comment by RRShanbhag** [comment]
Ohhh thanks. I understand now. Thank you for the quick replies. Will close this issue as soon as I try it tomorrow and get the result.

**Comment by rrhitman** [comment]
Ohhhhh I understand now. Thank you for the quick replies. I will try them tomorrow and close this thread as soon as it works. Thank you again.

**Comment by rrhitman** [comment]
Ok the error on the web page is no more shown. However, it is not printing anything as well. It is supposed to print the following: "TestLib::init: Hello World!!". What is wrong ? I tried setting WASM=0 and changing the browser from Mozilla firefox 52.9.0 to Mozilla Firefox 60.0 and Google chrome.  Both didn't work.

A normal hello world program works but not this. What is the mistake I am doing now ?

**Comment by rrhitman** [comment]
@kripken 
Hello,
Can you tell me as to why that error is coming?

Also, 
Like you said, I understood how to add the dynamic libraries in pre.js file that is available in $EMSCRIPTEN/third_party/lzma.js/pre.js . Now in the test_browser.py example, the --pre-js option is used to load the pre.js file. Is this necessary ? Or is it done automatically because this step was not mentioned in the Emscripten/linking page under General Dynamic Linking

**Comment by kripken** [comment]
The `--pre-js` option is one way to add the JS that sets up `Module.dynamicLibraries`. You could also do that in another script tag, or edit the emitted JS, etc.

**Comment by rrhitman** [comment]
Hello Kripken,

Thank you for helping me with understanding pre-js. However, I have a new issue, I use system library(i.e. cout) in one of the Side modules. So, when I compiled and ran I got the following error. 
![image](https://user-images.githubusercontent.com/41010610/43149038-86d983d2-8f34-11e8-96bb-fea3f40bdc79.png)


Hence, I did as it said. Now I am getting this warning and the same error continues.
![image](https://user-images.githubusercontent.com/41010610/43148789-0432edb0-8f34-11e8-9e13-41d453f0d968.png)

What am I doing wrong here ? This is my current Emcc flags I am using

`emcc --emrun -s ASSERTIONS=1 -s BINARYEN_ASYNC_COMPILATION=1 -s SIDE_MODULE=1 -s LINKABLE=1 -s BUILD_AS_SHARED_LIB=1 -s WASM=1 testlib.cpp -o testlib.bc`

`emcc --emrun -s ASSERTIONS=1 -s BINARYEN_ASYNC_COMPILATION=1 -s SIDE_MODULE=1 -s LINKABLE=1 -s BUILD_AS_SHARED_LIB=1 -s WASM=1 testlib.bc -o testlib.wasm`

`emcc --emrun -s ASSERTIONS=1 -s BINARYEN_ASYNC_COMPILATION=1 -s MAIN_MODULE=1 -s WASM=1 -s EMCC_FORCE_STDLIBS=1 main.cpp -o test.html`

I have added the module.dynamicLibraries=['test.wasm'] in the pre-js file.

What wrong am I doing here ?

**Comment by rrhitman** [comment]
I found out that EMCC_FORCE_STDLIBS is actually environment variable. After setting that, I am getting error that

`ReferenceError: _emscripten_glTexParameterf$legalf32 is not defined`

I found a link who has pointed out this issue. https://github.com/kripken/emscripten/issues/5436 .But Soultion is not mentioned. Could you please tell me what to do?

**Comment by rrhitman** [comment]
Hello Kripken,

As a work around to the previous error, I set EMCC_FORCE_STDLIBS=libc, libcxxabi and so on. As I did not need gl.bc. However, now I am facing another weird error. 

![image](https://user-images.githubusercontent.com/41010610/43211318-4051195e-8fff-11e8-9eca-86a46d8c34ba.png)

Could you please tell me as to why this is happening ?

**Comment by kripken** [comment]
That stack overflow error looks weird, but maybe it's just reporting the size wrong. It's possible you need to increase the stack size (TOTAL_STACK), or there is a bug in the code that is allocating too much on the stack incorrectly.

**Comment by rrhitman** [comment]
Hello Kripken, 
Thank you for the advice. I added the option -s OUTLINING_LIMIT=50000 to my library file when compiling and the error stopped. But now I am getting a couple of warnings and followed by error : 

```
warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
warning: trying to dynamically load symbol '__ZZNK14CCfSmartString3GetEvE14rgbyEmptyCFSTR' (from '0,97,115,109,1,0,0,0,0,15,6,100,121,108,105,110,107,240,198,192,2,4,128,8,0,1,128,1,20,96,4,127,127,127,127,1,127,96,3,127,127,127,1,127,96,1,127,1,127,96,1,127,0,96,2,127,127,1,127,96,0,1,127,96,5,127,127,127,127,127,1,127,96,2,127,127,0,96,2,127,124,0,96,3,127,127,127,0,96,0,0,96,2,127,127,1,124,96,6,127,127,127,127,127,127,1,127,96,6,127,127,127,127,127,127,0,96,4,127,127,127,127,0,96,7,127,127,127,127,127,127,127,1,127,96,5,127,127,127,127,127,0,96,1,127,1,125,96,1,127,1,124,96,0,1,124,2,224,18,84,3,101,110,118,6,109,101,109,111,114,121,2,0,128,2,3,101,110,118,5,116,97,98,108,101,1,112,0,128,8,3,101,110,118,10,109,101,109,111,114,121,66,97,115,101,3,127,0,3,101,110,118,9,116,97,98,108,101,66,97,115,101,3,127,0,3,101,110,118,5,97,98,111,114,116,0,3,3,101,110,118,11,115,101,116,84,101,109,112,82,101,116,48,0,3,3,101,110,118,11....85,83,46,85,84,70,56') that already exists (duplicate symbol? or weak linking, which isn't supported yet?)
```

```
uncaught exception: abort() at jsStackTrace@http://localhost:6931/test.js:1229:13
stackTrace@http://localhost:6931/test.js:1246:12
abort@http://localhost:6931/test.js:66473:44
_abort@http://localhost:6931/test.js:8906:7
__ZNSt3__212_GLOBAL__N_121__throw_runtime_errorERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE@http://localhost:6931/test.js line 1924 > WebAssembly.Module:wasm-function[3058]:0x10b7c9
__ZNSt3__214collate_bynameIcEC2ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEj@http://localhost:6931/test.js line 1924 > WebAssembly.Module:wasm-function[1360]:0xf2c8d
__ZNSt3__26locale5__impC2ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEj@http://localhost:6931/test.js line 1924 > WebAssembly.Module:wasm-function[239]:0x84152
__ZNSt3__26localeC2EPKc@http://localhost:6931/test.js line 1924 > WebAssembly.Module:wasm-function[1424]:0xf4ea2
@http://localhost:6931/test.js line 408 > WebAssembly.Module:wasm-function[458]:0x45c8a
@http://localhost:6931/test.js line 408 > WebAssembly.Module:wasm-function[299]:0x41959
callRuntimeCallbacks@http://localhost:6931/test.js:1457:7
ensureInitRuntime@http://localhost:6931/test.js:1498:3
doRun@http://localhost:6931/test.js:66398:5
run/<@http://localhost:6931/test.js:66415:7
setTimeout handler*run@http://localhost:6931/test.js:66411:5
runCaller@http://localhost:6931/test.js:66323:29
removeRunDependency@http://localhost:6931/test.js:1697:7
@http://localhost:6931/test.js:1736:11
```

Could you tell me what this warning and error means ?

**Comment by rrhitman** [comment]
Also, to your previous reply, I forgot to mention, I had also added the -Os option during compilation. When I removed that I got the Stackover flow error again. So, as you mentioned I increased the TOTAL_STACK and the error did not go. So, how do I find out which function or what is it that causing this error ?

**Comment by kripken** [comment]
The `trying to dynamically load symbol` warning is saying that that symbol `__ZZNK14test3GetEvE14rgbyEmptyINT` is being loaded twice - it would be good to find out why that is, as it could be an error. But it may also be safe to ignore.

The `throw_runtime_error` error is not clear - I think it's C++ code hitting an error condition. From the stack trace I'm not sure if it's in a system library or your code. I'd build with `-g` so the stack trace is clearer, that might help. You may also need to add debug statements or such to see why C++ is throwing that.

**Comment by rrhitman** [comment]
Hello Kripken,
Thank you for the advice. For now I have decided to ignore the warning. Also, thank to your advice, I found out where the error is coming from. I am using locale constructor with const char* argument as "en_US.UTF8". I commented this portion out and it went passed that error. However, this works in GCC.

Is there something extra I need to add to make it work for en_US.UTF8 ?

**Comment by rrhitman** [comment]
Also, my main function takes in command-line arguments from main. How do I do it using emrun? Do you have an example ?

**Comment by rrhitman** [comment]
I don't know why this error is coming at the moment. Could please as to why this might be happening?
![image](https://user-images.githubusercontent.com/41010610/43524794-2705928a-956e-11e8-9771-3e12ec1d3748.png)

I am basically using General Dynamic Linking. I have a shared library(-s SIDE_MODULE) libtest.bc which I recompiled to libtest.wasm. 

My main module is compiled with following options.
`--emrun -v -O0 -g4 -s SAFE_HEAP=1 -s STACK_OVERFLOW_CHECK=1 -s ASSERTIONS=2 -s OUTLINING_LIMIT=50000 -s TOTAL_STACK=6*1024*1024 -s DEMANGLE_SUPPORT=1 -s BINARYEN_ASYNC_COMPILATION=1 -s MAIN_MODULE=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 --pre-js ${PROJECT_SOURCE_DIR}/pre.js`

My pre.js file contains the following:
`Module.dynamicLibraries = ['/libtest.wasm'];`


It compiles fine. But I keep getting that error every 5s during run time. My main function doesn't even get executed. Please help

**Comment by kripken** [comment]
Search for `preload_dynamicLibraries` in the JS (it comes from src/preamble.js). We create the dependency before loading libs, then remove it after they are loaded. So if there is a network problem in loading them, or a wasm problem to compile them, the dependency may not get removed. You should see an error in the devtools that indicates what went wrong (the console may be enough, but the network devtools can help if it's a network issue specifically).

**Comment by rrhitman** [comment]
Hey Kripken,

Thanks for reply. Looking at the preamble.js, I learnt a lot. However, I still couldn't figure out why this problem is happening. Like you said, I checked in network devtools to see if its loading problem. I can see that it has been loaded. So according to what you said, now I feel that its something to do with wasm problem to compile them. However, I don't see any problems thrown in devtools about any compiling problem. Also, I don't know how to see if there is a compiling problem in the first place. 

Below, is the picture of the Network Devtools
![image](https://user-images.githubusercontent.com/41010610/43600768-7e7ecce8-9659-11e8-9f9e-496fdda56dcf.png)
Can you tell me what you think that might be the problem for this to happen ? Could it be because I am missing any like system libraries ? 

Lastly, when you say " a wasm problem to compile them" what do you mean? I already built the library to .bc and then to .wasm and finally gave that to pre-js. Does it go through another round of compilation when loading it in the browser ?

**Comment by rrhitman** [comment]
Also, kripken, can you explain what the problem is regarding SIDE modules which are linkable using Pthreads ? Or can you point me in the direction where I can learn about the issue ?

**Comment by kripken** [comment]
In general, both SIDE_MODULE and USE_PTHREADS are non-default and less-tested options - so in each of them you need to expect some rough edges, and especially when combining multiple such potions.

I'm not sure offhand why they wouldn't work together, but it's possible we just have not looked to see if they do. If we throw an error on that combination now, one thing to check might be to remove the error and see if any tests in the test suite fail - but, I suspect we may not have any tests for that combination.

**Comment by rrhitman** [comment]
Hello Kripken, 
Thank you for the reply. I still haven't got try your advice yet as I have been busy solving another issue. After losing the whole weekend on this is, I have no choice but to come to you again. I am trying to load one of the side modules of my application and I facing this error:

> Error in loading dynamic library: LinkError: import object field '__ZN8foobarIT0_EEii' is not a Function

After following the instruction in this below StackOverflow link which looked to be close to what I am facing,

> https://stackoverflow.com/questions/44346670/webassembly-link-error-import-object-field-dynamictop-ptr-is-not-a-number

  I still get the same error. Do you have any thoughts as to why I am getting this error ? Please help. Any suggestion is welcomed.

**Comment by kripken** [comment]
I suggest trying #6963, which fixes issues that have that symptom, so it could be it.

**Comment by rrhitman** [comment]
Hello Kripken,

I am facing another error right now. So, yesterday, I was building my project with 1.38.8 and it was working fine. But then I saw that emscripten has updated to 1.38.11 so, I updated it. So then I started getting LLVM errors and I couldn't fix it. So, I uninstalled the emsdk by removing the emsdk folder and reinstall to the latest one. This time, my project compiled but took a lot of time. And at runtime I get this following error:

![image](https://user-images.githubusercontent.com/41010610/44278658-aec91d80-a21c-11e8-916c-84c4bcb95df0.png)

Searching online, I found that this symbol is coming from some system library. I don't know what to do now and how to get this fixed. And it would be nice if I can work with 1.38.11 itself. I want to be up to date with the compiler. Please help

**Comment by kripken** [comment]
@rrhitman - that is probably the `size_t` change. You should make sure to rebuild all files with the new emsdk, and not mix bitcode from an older version. (Also `./emcc --clear-cache` may help if a problem happened with system library building, but that should be automatic.)

See https://github.com/kripken/emscripten/pull/5916

**Comment by rrhitman** [comment]
Hello Kripken,

Thank you for the reply. I will try that this weekend. Meanwhile, I got back to the previous Emscripten version i.e. 1.38.8 and continued building my application in WebAssembly. In your one of the earlier advice (https://github.com/kripken/emscripten/issues/6837#issuecomment-410808072) regarding the using of -s LINKABLE and -s USE_PTHREADS at the same time, I commented out the error in emcc.py as shown below:
![image](https://user-images.githubusercontent.com/41010610/44425201-32567780-a559-11e8-9433-6f6ae80eca41.png)

N then compiled my side modules as follows: 
`emcc -s SIDE_MODULE=1 -s USE_PTHREADS=1 -s WASM=1 foo.cpp -o foo.bc `
Since my main module uses this side module by using dlopen method, I need to convert it to .wasm.
I use the same options as above to convert this to .wasm: 
`emcc -s SIDE_MODULE=1 -s USE_PTHREADS=1 -s WASM=1 foo.bc -o foo.wasm`

It prints out a huge Stacktrace and throws this weird error:

```
Fatal: error in validating output
Traceback (most recent call last):
  File "/home/devbuild/Web_proj/emsdk/emscripten/1.38.8/emcc", line 11, in <module>
    python_selector.run(__file__)
  File "/home/devbuild/Web_proj/emsdk/emscripten/1.38.8/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/devbuild/Web_proj/emsdk/emscripten/1.38.8/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/devbuild/Web_proj/emsdk/emscripten/1.38.8/emcc.py", line 2019, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/home/devbuild/Web_proj/emsdk/emscripten/1.38.8/emcc.py", line 2491, in do_binaryen
    shared.check_call(cmd)
  File "/home/devbuild/Web_proj/emsdk/emscripten/1.38.8/tools/shared.py", line 178, in check_call
    raise FatalError("'%s' failed" % " ".join(cmd))
tools.shared.FatalError: '/home/devbuild/Web_proj/emsdk/clang/e1.38.8_64bit/binaryen/bin/asm2wasm libs/foo.asm.js --total-memory=16777216 --trap-mode=allow -O1 --table-max=-1 --mem-max=-1 --enable-threads -o libs/foo.wasm' failed
Makefile:7: recipe for target 'foo.wasm' failed
make: *** [foo.wasm] Error 1
```
Why do you think I am getting this error? Please help

**Comment by kripken** [comment]
`error in validating output` might be a binaryen error, but I'm not sure - was there more context around that line? Building with EMCC_DEBUG=1 in the env might help.

If it's a binaryen validation error, if you can provide a testcase I can reproduce it with that would be good.
