### ISSUE TITLE
TypeError: start is not a function when using emscripten_sleep() and asyncify

### ISSUE THREAD

**Issue by ohnx** [emscripten-core/emscripten#12239]
**Version(s) affected:** `2.0.3`, `2.0.4`

I'm getting this error when trying to use `emscripten_sleep()`:
`TypeError: start is not a function. (In 'start()', 'start' is undefined)`

The line is coming from `handleSleep`; it looks like `var start = Asyncify.getDataRewindFunc(Asyncify.currData);` is returning nothing... Someone who was helping me debug mentioned this:

> stepping through the asyncify js in a situation where it fails, it seems that when `emscripten_sleep` is called, that calls `handleSleep`, which then calls `allocateData`, which IIUC should store the resume target by calling `setDataRewindFunc`, and the latter gets that target by taking the top (bottom?) of the `exportCallStack`
> however, due to reasons I don't understand yet, the `exportCallStack` is empty at that point

[zip file of sample code to reproduce issue](https://github.com/emscripten-core/emscripten/files/5234503/minimal.zip)

**Comment by sammax** [comment]
I bisected it to https://github.com/emscripten-core/emscripten/commit/43fcfd2938b72c57373a910ece897b27aa298852.

IIUC the embind setup creates some indirect invocation code to call exports, and it skips that if the signature does not contain `'j'`. The signature is `'vi'` for the function you export, so it directly returns the wasm table entry instead of creating the invocation code. But that invocation code is needed for async because it pushes the export that was called onto a stack which is later used by the asyncify code to find out what it needs to call.

**Comment by sbc100** [comment]
@kleisauke
