### ISSUE TITLE
Possible regression in 1.38.26 - Missing dynCall and problem with WASM memory

### ISSUE THREAD

**Issue by trzecieu** [emscripten-core/emscripten#8018]
Hi,
After testing latest release I've started to see runtime errors:
```
// Browser console for WASM build
failed to asynchronously prepare wasm: LinkError: import object field 'memory' is not a Memory
LinkError: import object field 'memory' is not a Memory ff.js:1787:9
```
Possible related to: https://github.com/emscripten-core/emscripten/pull/7975

```
// for ASM.js build
Error: Runtime.dynCall is not a function
```
When was used like: `Runtime.dynCall("vii", callback, [x,  y]);`
Possible ripple effect of: https://github.com/emscripten-core/emscripten/commit/6b6c0ec5f7c9bcddd03c367e5b8bfe8feb8c8222, but hard to tell at first glance

**Comment by kripken** [comment]
Was this an update from a very old version? The Runtime object has been removed for quite some time at this point (to fix that issue, you should remove `Runtime.` from your code, and just call `dynCall`).

I don't have a guess about the 'memory is not a Memory' bug, that doesn't look familiar, and I don't think that PR could cause it. If nothing easier, it might be best to just bisect.

**Comment by trzecieu** [comment]
Hi, interesting. I did a check between 1.38.25 and 1.38.26. 
Version 1.38.25 works fine.
I'll try to narrow it down. Cheers

**Comment by trzecieu** [comment]
**Runtime.dynCall**
Hi, so the challenge is to provide compatibility for both versions, but with `Runtime` object it will be not a problem as we can wrap/abstract/mock/implement such JS calls. 
Runtime object hasn't been removed thou, it's empty now:
https://github.com/emscripten-core/emscripten/blob/b076e8998ef86dcff1dc9ffe28a1cd3ff7279d5a/src/support.js#L818-L825
As a result of https://github.com/emscripten-core/emscripten/pull/7955/files#diff-6d4bb79610683d9749d2cbb62e708d88 which looks fine in general and definitely it's not a regression as I thought. 

**LinkError: import object field 'memory' is not a Memory**
It's caused by https://github.com/emscripten-core/emscripten/pull/7925 It's more like a surprise, as we've used `Module['wasmMemory']` for passing preallocated buffer. It's definitely not a blocker as it can be fixed by:
```js
window.wasmMemory = custom_preallocate_buffer();
```

**hiding crypto implementation**
This is was introduced by: https://github.com/emscripten-core/emscripten/pull/6208
Exactly here: https://github.com/emscripten-core/emscripten/pull/6208/files#diff-349daa47efec0b4193bc556a841c6920R1309
That due JavaScript hoisting mechanism, an `undefined` variable hides system `crypto`
Simplified exampe: https://jsfiddle.net/n24ay6o9/2/
Fix: https://github.com/emscripten-core/emscripten/pull/8031

**Comment by trzecieu** [comment]
Thanks!
