### ISSUE TITLE
python em++.py error: AttributeError: 'module' object has no attribute 'fullmatch'

### ISSUE THREAD

**Issue by kevzettler** [emscripten-core/emscripten#11582]
have installed the latest using `emsdk`. I am trying to compile a really old project. Like maybe last working with `1.29.4` I'm not sure what this python error is about:

```
/Users/kevzettler/code/emsdk/upstream/emscripten/em++  -O3  -s USE_SDL=2 -s TOTAL_MEMORY=134217728 -s ALLOW_MEMORY_GROWTH=0 -s ASYNCIFY=1 -s ASYNCIFY_WHITELIST=@emterpretify.txt -s FETCH=1   -s WASM=0  -o dosbox.html dosbox.o  cpu/libcpu.a debug/libdebug.a dos/libdos.a fpu/libfpu.a  hardware/libhardware.a gui/libgui.a ints/libints.a misc/libmisc.a shell/libshell.a hardware/serialport/libserial.a libs/gui_tk/libgui_tk.a
Traceback (most recent call last):
  File "/Users/kevzettler/code/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/Users/kevzettler/code/emsdk/upstream/emscripten/emcc.py", line 1286, in run
    apply_settings(settings_changes)
  File "/Users/kevzettler/code/emsdk/upstream/emscripten/emcc.py", line 435, in apply_settings
    value = str(expand_byte_size_suffixes(value))
  File "/Users/kevzettler/code/emsdk/upstream/emscripten/emcc.py", line 393, in expand_byte_size_suffixes
    match = re.fullmatch(r'(\d+)\s*([kmgt]?b)?', value, re.I)
AttributeError: 'module' object has no attribute 'fullmatch'
make[4]: *** [dosbox.html] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by sbc100** [comment]
Ah, it looks like fullmatch is python2 - only.     I guess we don't have much python2 coverage anymore :(

One quick solution for you would be install python3.
