### ISSUE TITLE
wasmTable.get(...) is not a function when using wasm object files

### ISSUE THREAD

**Issue by erikmchut** [emscripten-core/emscripten#12559]
I recently upgraded to emscripten 2.0.7 from a 1.XX.X release and did some benchmarking between LTO and non-LTO binaries on the new version. In the process, I encountered an error in in one of our applications that only repros when using wasm object files (non-LTO).

The error has the following stack trace:

TypeError: wasmTable.get(...) is not a function
    at invoke_vi (omniscope-asm.js:9)
    at :8889/omniscope-asm.wasm:wasm-function[1717]:0x922a0
    at invoke_viiii (omniscope-asm.js:9)
    at :8889/omniscope-asm.wasm:wasm-function[2697]:0x1046d8
    at :8889/omniscope-asm.wasm:wasm-function[2645]:0x100c31
    at invoke_viii (omniscope-asm.js:9)
    at Df (:8889/omniscope-asm.wasm:wasm-function[4667]:0x20a033)
    at onProcessGpu (bundle.js:11968)
    at eval (camera-loop.js:176)
    at cb (callback-manager.js:225)

The same code runs fine when linked using bitcode objects. Could this be related to #12296 ? @sbc100  If so, are we missing something when linking wasm files?

**Comment by sbc100** [comment]
This means that `invoke_vi` function is being called with an invalid table index.  Most likely table index 0.   I've been meaning to add a assertion here when table index 0 is requested because that is essentially a null function pointer exception. 

Could you add a `console.log()` to `invoke_vi` to find out that index is being used?

Are you using MAIN_MODULE/SIDE_MODULE by any chance?

Can you see what version this started to occur in?  Did it work in 2.0.0 for example?

**Comment by erikmchut** [comment]
> Could you add a console.log() to invoke_vi to find out that index is being used?
console.log shows that the calls to invoke_vi that fail have index=0.

> Are you using MAIN_MODULE/SIDE_MODULE by any chance?

> Can you see what version this started to occur in? Did it work in 2.0.0 for example?
Not easily. This is the first version of emscripten in which we had a working build with the wasm llvm backend and wasm object files. Is there anything else to try that would also get at the issue?

**Comment by sbc100** [comment]
> > Could you add a console.log() to invoke_vi to find out that index is being used?
> 
> console.log shows that the calls to invoke_vi that fail have index=0 as you suspected.

Well that is good sign in way because it means that we your have a null function pointer in your program somewhere.

Can you try building with `-g` or `--profiling-functions` to find out what the calling function is and where the function pointer which is argument 0 to `invoke_vi` is coming from?    I assume because its calling invoke_xx that this relates to exception handling.   @aheejin might have some clues.

Is there anything else unusual about your program?  Can you share your linker flags (or at least `-s` settings)?

> 
> > Are you using MAIN_MODULE/SIDE_MODULE by any chance?
> 
> No.
> 
> > Can you see what version this started to occur in? Did it work in 2.0.0 for example?
> 
> Not easily. This is the first version of emscripten in which we had a working build with the wasm llvm backend and wasm object files. Is there anything else to try that would also get at the issue?

You mean version 2.0.1 through 2.0.6 don't work for you?

**Comment by sbc100** [comment]
Is there any way to build your application without exceptions (at least as a test to see if that fixes the issue)?

**Comment by erikmchut** [comment]
The current compilation is -g0 -03, so I would expect no symbols and exceptions disabled by default. I'll try rebuilding with different options. If this is indeed a null-dereference as you suggest, should I just build with `-fsanitize=undefined` ?

**Comment by sbc100** [comment]
Building with `--profiling-functions` is the lowest impact way to get symbols in your backtrace yes.

Building with sanitizers would be great, but I do also worry that this null pointer is perhaps not present in the source language but an indirect function pointer generated by the exception handling lowering pass which most likely generated the call to `invoke_xxx` in the first place.    If I'm correct I'm not sure the sanitizers will help.   But its worth a try.

**Comment by sbc100** [comment]
You might want to look at the instruction that called the invoke_xx with the null pointer `omniscope-asm.wasm:wasm-function[1717]:0x922a0`.    To do this I would use something like `wasm-objdump -d`  look for function 1717.. it should contain the instruction at offset 0x922a0.  I might give you a clue as to what line in the input source it corresponds to.

**Comment by erikmchut** [comment]
Thanks for the suggestions. I'll give them a try, and see what I can figure
out.

**Comment by erikmchut** [comment]
With `--profiling-funcs`, I get the following trace:

```
 TypeError: wasmTable.get(...) is not a function
    at invoke_vi (omniscope-asm.js:8828)
    at c8::GlRealityFrame::draw(unsigned int, c8::GlRealityFrame::Options, c8::LoggingContext*) (:8889/omniscope-asm.wasm:wasm-function[1901]:0xb1fbf)
    at invoke_viiii (omniscope-asm.js:8850)
    at c8::CameraFeaturesCanvasViewData::drawGl(c8::FrameInput&, c8::LoggingContext*) (:8889/omniscope-asm.wasm:wasm-function[5020]:0x271a95)
    at c8::OmniscopeView::drawGl(c8::FrameInput&, c8::LoggingContext*) (:8889/omniscope-asm.wasm:wasm-function[4760]:0x2191ff)
    at invoke_viii (omniscope-asm.js:8784)
    at c8EmAsm_glProcess (:8889/omniscope-asm.wasm:wasm-function[4515]:0x1c9db2)
    at onProcessGpu (bundle.js:11968)
    at eval (camera-loop.js:176)
    at cb (callback-manager.js:225)

```
Next I added log statements in each of the lines in c8::GlRealityFrame::draw, finding that the error occurs on the call to the OpenGL method;
`glBindVertexArray(0);`

The method `glBindVertexArray` is actually a function pointer, which is defined as a static global:

`static auto glBindVertexArray = (PFNGLBINDVERTEXARRAYOESPROC) eglGetProcAddress("glBindVertexArrayOES");
`

I've confirmed that the function pointer is non-NULL.

This code works with bitcode objects, and in prior emscripten versions (also with bitcode objects). Perhaps there something different in how OpenGL extension methods should be bound or linked?

**Comment by sbc100** [comment]
Can you looks at the disassembly around the call to `invoke_vi` to see where it fetches the first argument (which appears to be null) from?   I imagine it should be loading it from memory at the location of the `eglGetProcAddress` pointer?

**Comment by erikmchut** [comment]
Here is a disassembly around the invoke_vi call. 606104 == 0x93f98, the address of the function pointer. You are correct, the value stored in this address is null.

Armed with this knowledge, my question is now: why does `eglGetProcAddress("glBindVertexArrayOES");` return nullptr here? Looking at the code, it seems  like eglGetProcAddress is [rewritten by binaryan postprocessing](https://github.com/emscripten-core/emscripten/blob/e179b57d11fcf385f0b9b2ed70a29da333bf71c2/src/deps_info.json#L51) to [emscripten_GetProcAddress](https://github.com/emscripten-core/emscripten/blob/7ad70139bb0fcfa707959b6be1c7bce75188fea5/system/lib/gl/gl.c#L1800) which parses the string `"glBindVertexArrayOES"` and returns the address of the glBindVertexArray method (or some c wrapper to it that can call the corresponding WebGL method). Does this process differ when linking wasm objects?


```
 0b1fcf: 36 02 00                   |               i32.store 2 0
 0b1fd2: 41 98 ff 24                |               i32.const 606104  # <-- This matches the function pointer address
 0b1fd6: 28 02 00                   |               i32.load 2 0
 0b1fd9: 20 04                      |               local.get 4
 0b1fdb: 28 02 8c 03                |               i32.load 2 396
 0b1fdf: 10 04                      |               call 4 <invoke_vi>   # <-- invoke_vi call
 0b1fe1: 41 c0 88 25                |               i32.const 607296
 0b1fe5: 28 02 00                   |               i32.load 2 0
 0b1fe8: 21 00                      |               local.set 0
```

**Comment by sbc100** [comment]
Nice job debugging this so far.   I don't know of any reason why LTO would change anything about this process.   

At what point is eglGetProcAddress being called?  Is it being run during a constructor, or as part of your normal application startup code?  Do you see it return null there?

**Comment by erikmchut** [comment]
eglGetProcAddress is being called during static initialization to initialize the function pointer which is a static global.

I was observing that the value is null right before it was called. It shouldn't be changing, so I'm currently working under the assumption that it is initialed to null.

**Comment by sbc100** [comment]
I suspect it may relate to the static init stuff.   Maybe try initializing in a startup function other than static initialization?  (i.e. at the beginning of main?).

Can you log the value returned in both cases (static init vs main)?

**Comment by erikmchut** [comment]
(re-reading my last post, I'm chuckling because I would answer myself that c++ static initialization order is likely to blame for the situation I'm describing). I'll try lazy initialization and see if that does anything different.

**Comment by erikmchut** [comment]
And that fixes it. Great real-world example of C++'s indeterminate static initialization order. Linking gets changed, and the initializer order changes with it.  Thanks for the help debugging – and apologies for the user error. :-)
