### ISSUE TITLE
std::quick_exit cannot compile on em++-1.20.0

### ISSUE THREAD

**Issue by usagi** [emscripten-core/emscripten#2464]
Occerred compile error with `std::quick_exit`.

a.cxx:

``` C++
#include <cstdlib>
int main() { std::quick_exit( EXIT_SUCCESS ); }
```

compile: `em++ -std=c++11 a.cxx`

```
a.cxx:2:28: error: no member named 'quick_exit' in namespace 'std'
auto main( ) -> int { std::quick_exit( EXIT_SUCCESS ); }
                      ~~~~~^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
```

However, `int main() { ::quick_exit( EXIT_SUCCESS ); }` can compile but occuerred `warning: unresolved symbol: quick_exit`.

Is it bug?

---

ref: 
- https://github.com/kripken/emscripten/blob/master/system/include/libcxx/cstdlib#L78
- C++ spec p.438-439 §18.5 Start and termination

**Comment by barracuda156** [comment]
Just got the same error on PowerPC with gcc 12.3.0:
```
error: 'quick_exit' is not a member of 'std'
```

**Comment by sbc100** [comment]
> ```c++
> #include <cstdlib>
> int main() { std::quick_exit( EXIT_SUCCESS ); }
> ```

I confirmed that std::quick_exit is available in emscripten now at compile time, and uploaded a change to make sure its not undefined at link time: https://github.com/emscripten-core/emscripten/pull/19891

**Comment by sasmaster** [comment]
weird but I am on 4.0.6 and the linker fails to find  `std::quick_exit`.

**Comment by sbc100** [comment]
I just tried compiling the simple test program with 4.0.6 and it works fine:

```
$ cat test.cc
#include <cstdlib>
int main() { std::quick_exit( EXIT_SUCCESS ); }
$ ./emcc test.cc
```

If the problem persists for you can you try this simple example?  if that works but your program doesn't can you share more info about your program.  At least the full link command would useful.
