### ISSUE TITLE
TypeError: getTempRet0 is not a function

### ISSUE THREAD

**Issue by shooshx** [emscripten-core/emscripten#10339]
I'm compiling my code with -O3 and -s WASM=0 and I'm getting this runtime error which happens inside function _ZN17compiler_builtins3int4sdiv3Mod4mod_17h2cbb7bbf36e41d68E($0 $1)
This doesn't happen in with -O0 and I did some -O3 compiles that did work just a few minutes ago, not much has changed since then.

version:
emcc (Emscripten gcc/clang-like replacement) 1.39.5 (commit 369013943283939412fb2807bb0d2ded8ebd5a9e)

**Comment by sbc100** [comment]
Can you provide a repro case?   I assume you using the llvm backend which means wasm2js is being run to convert the wasm to JS.

**Comment by shooshx** [comment]
Well, I don't have a minimal repro but I pushed code code it happens on to here:
https://github.com/shooshx/happysolver/tree/emscripten_temp_bug
The build command is in
emscripten/build_rel.bat

**Comment by kripken** [comment]
Hmm, when I build with upstream on 1.39.6 (master) I get
```
shared:ERROR: For wasm, TOTAL_MEMORY must be a multiple of 64KB, was 20000000
```
I tried setting memory to 20MB. After that I also had to fix
```diff
diff --git a/emscripten/js_main.cpp b/emscripten/js_main.cpp
index 9c2d284..0f69db9 100644
--- a/emscripten/js_main.cpp
+++ b/emscripten/js_main.cpp
@@ -1,6 +1,6 @@
 #include <emscripten.h>
-#include <html5.h>
-#include <trace.h>
+#include <emscripten/html5.h>
+#include <emscripten/trace.h>
 #include <emscripten/bind.h>
 
 #include <EGL/egl.h>
```
At that point it builds, and I don't see getTempRet0 in the output, so I don't think I am reproducing the problem. But given I had to make those changes to build, perhaps somehow you were building on an older version of the compiler by mistake, like maybe another one was in your path, different than the one you get the version from?
