### ISSUE TITLE
The socket code does not work properly, in versions after 1.39.12

### ISSUE THREAD

**Issue by realray808** [emscripten-core/emscripten#11179]
I have tcp code as following：
```
if(connect(sockfd, (struct sockaddr*)&servaddr, sizeof(servaddr)) < 0 && errno != EINPROGRESS){
        printf("connect error: %s(errno: %d)\n",strerror(errno),errno);
        return 0;
    }
while (1)
    {
        /* code */
        fd_set fdr;
        fd_set fdw;
        int res;
        cout << "sockfd " << sockfd << endl;
        FD_ZERO(&fdr);
        FD_ZERO(&fdw);
        FD_SET(sockfd, &fdr);
        FD_SET(sockfd, &fdw);
        res = select(64, &fdr, &fdw, NULL, NULL);
    ...
	}
```
When I use 1.39.11 or earlier, it works. But  when i update the version of emscripten to 1.39.12 or later, this code can be successfully complied but not working. It seems that the select function is not working properly, it is not returning anything.
```
test.worker.js:170 worker.js onmessage() captured an uncaught exception: Error: Bad file number
onmessage @ test.worker.js:170
test.worker.js:171 Error
    at new ErrnoError (http://24.64.213.123:8080/test.js:4328:60)
    at ___sys__newselect (http://24.64.213.123:8080/test.js:2529:28)
    at wasm-function[87]:0x3420
    at wasm-function[49]:0x1de7
    at wasm-function[45]:0x1997
    at Module._main (http://24.64.213.123:8080/test.js:7599:32)
    at ___call_main (http://24.64.213.123:8080/test.js:2423:24)
    at wasm-function[1593]:0x2835c
    at wasm-function[1627]:0x2929c
    at Object.Module.dynCall_ii (http://24.64.213.123:8080/test.js:7858:38)
onmessage @ test.worker.js:171
test.html:1246 pthread sent an error! http://24.64.213.123:8080/test.worker.js:172: Uncaught Error: Bad file number
```
My compile command is as follows:
em++ tcp.cpp -o test.html -s USE_PTHREADS -s PROXY_TO_PTHREAD

**Comment by kripken** [comment]
If you can provide a small testcase that could help. If not, I would bisect to find where this broke.

**Comment by realray808** [comment]
> If you can provide a small testcase that could help. If not, I would bisect to find where this broke.
Thanks for your reply.
Also, I try to compile the tests/sockets/test_sockets_echo_client.c with command 
`emcc test_sockets_echo_client.c -o test.html -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1`,
there is a same error. But it works properly without `-s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1`. Can you try it?
And my websocket server is a simple demo using uWebSockets library.

**Comment by kripken** [comment]
Thanks @realray808 , I bisected it to
```
a341c88f404e48fc45be9a2143d155942c84e798 is the first bad commit
commit a341c88f404e48fc45be9a2143d155942c84e798
Author: Sam Clegg <sbc@chromium.org>
Date:   Sun Mar 22 20:31:06 2020 -0400

    Rename JS syscalls to have meaningful names (#10750)
    
    Within musl code they are still called __syscallNN, but we can use
    `import_name` attribute to import them via a more meaningful name.
    
    We supply aliases under fastcomp that doesn't support `import_name`.

```

cc @sbc100 

My steps to reproduce: I ran
```
./tests/runner.py  sockets.test_sockets_echo
```
and at each step cleared the cache + applied this diff:
```diff
diff --git a/src/jsifier.js b/src/jsifier.js
index 11467aebc..a5b5ffe38 100644
--- a/src/jsifier.js
+++ b/src/jsifier.js
@@ -46,7 +46,8 @@ var NEED_ALL_ASM2WASM_IMPORTS = BINARYEN_TRAP_MODE == 'js';
 // the current compilation unit.
 // Also set for STANDALONE_WASM since the _start function is needed to call
 // static ctors, even if there is no user main.
-var HAS_MAIN = ('_main' in IMPLEMENTED_FUNCTIONS) || MAIN_MODULE || SIDE_MODULE || STANDALONE_WASM;
+console.warn('has main calc', IMPLEMENTED_FUNCTIONS, MAIN_MODULE, SIDE_MODULE, STANDALONE_WASM);
+var HAS_MAIN = true;//('_main' in IMPLEMENTED_FUNCTIONS) || MAIN_MODULE || SIDE_MODULE || STANDALONE_WASM;
 
 // Mangles the given C/JS side function name to assembly level function name (adds an underscore)
 function mangleCSymbolName(f) {
diff --git a/src/modules.js b/src/modules.js
index 2848d6007..48e457d0e 100644
--- a/src/modules.js
+++ b/src/modules.js
@@ -156,7 +156,7 @@ var LibraryManager = {
       libraries.push('library_webgpu.js');
     }
 
-    if (BOOTSTRAPPING_STRUCT_INFO) libraries = ['library_bootstrap_structInfo.js', 'library_formatString.js'];
+    if (BOOTSTRAPPING_STRUCT_INFO) libraries = ['library_bootstrap_structInfo.js', 'library_formatString.js', 'library_stack_trace.js'];
 
     // Deduplicate libraries to avoid processing any library file multiple times
     libraries = libraries.filter(function(item, pos) {
diff --git a/tests/test_sockets.py b/tests/test_sockets.py
index d93fb7c5e..8fc3fa650 100644
--- a/tests/test_sockets.py
+++ b/tests/test_sockets.py
@@ -118,7 +118,7 @@ class CompiledServerHarness(object):
       npm_checked = True
 
     # compile the server
-    proc = run_process([PYTHON, EMCC, path_from_root('tests', self.filename), '-o', 'server.js', '-DSOCKK=%d' % self.listen_port] + self.args)
+    proc = run_process([PYTHON, EMCC, path_from_root('tests', self.filename), '-o', 'server.js', '-DSOCKK=%d' % self.listen_port] + self.args + [ '-s', 'ERROR_ON_UNDEFINED_SYMBOLS=0', '-s', 'EXPORTED_FUNCTIONS=["_main", "_htons"]']) # waka
     print('Socket server build: out:', proc.stdout or '', '/ err:', proc.stderr or '')
 
     process = Popen(NODE_JS + ['server.js'])
@@ -192,7 +192,11 @@ class sockets(BrowserCore):
 
     for harness, datagram in harnesses:
       with harness:
-        self.btest(os.path.join('sockets', 'test_sockets_echo_client.c'), expected='0', args=['-DSOCKK=%d' % harness.listen_port, '-DTEST_DGRAM=%d' % datagram, sockets_include])
+        self.btest(os.path.join('sockets', 'test_sockets_echo_client.c'), expected='0', args=['-DSOCKK=%d' % harness.listen_port, '-DTEST_DGRAM=%d' % datagram, sockets_include,
+
+'-s', 'USE_PTHREADS=1', '-s', 'PROXY_TO_PTHREAD=1',  '-s', 'ERROR_ON_UNDEFINED_SYMBOLS=0', '-s', 'EXPORTED_FUNCTIONS=["_main", "_htons"]' # waka
+
+])
 
   def test_sdl2_sockets_echo(self):
     harness = CompiledServerHarness('sdl2_net_server.c', ['-s', 'USE_SDL=2', '-s', 'USE_SDL_NET=2'], 49164)
```

**Comment by sbc100** [comment]
Hmm.. maybe the socket syscall proxying code wasn't updated to use the new syscall names.  I'm not familiar with that code I'm afriad.

I guess that means we have no socket tests that use pthreads right now?

**Comment by kripken** [comment]
It looks like at least the last test in sockets.py uses pthreads, so there is *some* coverage. But maybe it's missing this case somehow.

**Comment by kripken** [comment]
And yes, I tinkered a little and it looks like `_newselect` is not proxied, which is the problem.

**Comment by kripken** [comment]
Ah, here's the bug:
```
    var match = /^__sys_[^_]*$/.exec(x);
```
`_newselect` is the one syscall whose name is prefixed with `_`...

**Comment by sbc100** [comment]
Oh.. nice find.  Can we just remove the `[^_]` part?

**Comment by kripken** [comment]
https://github.com/emscripten-core/emscripten/pull/11194 relaxes it. I'm not sure it's safe to remove entirely.

but that does not fully fix the test, see the PR. @realray808 does that PR fix your use case?

**Comment by kripken** [comment]
Once I fixed my test, it all passes, so I am hopeful that PR properly fixes and tests this issue now. But please confirm @realray808 if you can that the PR fixes things for you too. Or can test after we land it in the next release.
