### ISSUE TITLE
libcxx fails to build on LLVM 3.2 RELEASE tag on Windows.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#1019]
In the current incoming, the two files thread.cpp and condition_variable.cpp fail to build on Windows.

See http://clb.demon.fi:8112/builders/win-emcc-incoming-tests/builds/351/steps/Test%20emscripten%20incoming/logs/stdio

which reports

clang++: warning: argument unused during compilation: '-nostdinc++'
G:\Inttel-slave\win-emcc-incoming-tests\build\system\lib\libcxx\condition_variable.cpp:59:30: error: constexpr variable 'ts_sec_max' must be initialized by a constant expression
    _LIBCPP_CONSTEXPR ts_sec ts_sec_max = numeric_limits<ts_sec>::max();
                             ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
G:\Inttel-slave\win-emcc-incoming-tests\build\system\lib\libcxx\condition_variable.cpp:59:43: note: undefined function 'max' cannot be used in a constant expression
    _LIBCPP_CONSTEXPR ts_sec ts_sec_max = numeric_limits<ts_sec>::max();
                                          ^
G:\Inttel-slave\win-emcc-incoming-tests\build\system\include\libcxx\limits:443:61: note: declared here
    _LIBCPP_INLINE_VISIBILITY static _LIBCPP_CONSTEXPR type max() _NOEXCEPT {return __base::max();}
                                                            ^
1 error generated.

A manually preprocessed file of the above is available at https://dl.dropbox.com/u/40949268/emcc/bugs/preprocessed.cpp

which also fails to build if invoked manually with "clang++ -std=c++11 -m32 -U__i386__ -U__x86_64__ -U__i386 -U__x86_64 -Ui386 -Ux86_64 -U__SSE__ -U__SSE2__ -U__MMX__ -UX87_DOUBLE_ROUNDING -UHAVE_GCC_ASM_FOR_X87 -DEMSCRIPTEN -U__STRICT_ANSI__ -U__CYGWIN__ -D__STDC__ -Xclang -triple=i386-pc-linux-gnu -D__IEEE_LITTLE_ENDIAN -fno-math-errno -fno-ms-compatibility -nostdinc -nostdinc++ -Xclang -nobuiltininc -Xclang -nostdsysteminc -U__APPLE__ -U__linux__ -emit-llvm -c preprocessed.cpp"

A minimal failing example is available at https://dl.dropbox.com/u/40949268/emcc/bugs/constexpr_fail.cpp which fails as follows: https://dl.dropbox.com/u/40949268/emcc/bugs/constexpr_fail.txt

Linux and OSX builds of LLVM 3.2 RELEASE don't produce this error.

As a workaround, it is possible to fix the build by replacing line

```
_LIBCPP_CONSTEXPR ts_sec ts_sec_max = numeric_limits<ts_sec>::max();
```

with

```
ts_sec ts_sec_max = numeric_limits<ts_sec>::max();
```

in condition_variable.cpp and thread.cpp.

We will most likely submit a pull request that does this workaround to emscripten repo libcxx if llvm or libcxx folks can't recommend a nicer fix. Also, I'll try to test using clang trunk whether the issue still persists, since similar sounding bugs have been filed to clang tracker ( http://llvm.org/bugs/show_bug.cgi?id=11851 and http://llvm.org/bugs/show_bug.cgi?id=13702 )
