### PR TITLE
Fix wasm2js1.test_asyncify_lists_removelist_c. NFC

### PR DESCRIPTION
**Pull request by sbc100**
I updated the expectations for this failure in #15166 but it turns out
wasm2js generates a different type of error.  For now just check for
both types.  I wonder if we should try to have wasm2js be consistent
here?

### CODE REVIEW

**Comment by sbc100** [comment]
FWIW rather than a RuntimeError wasm2js generates:

```
+TypeError: FUNCTION_TABLE[($11_1 | 0)] is not a function
+    at $21 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:1259:39)
+    at $25 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:2660:6)
+    at $24 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:1624:15)
+    at $33 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:3005:18)
+    at $3 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:674:3)
+    at $7 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:765:6)
+    at ret.<computed> (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:6636:35)
+    at Module._main (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:6911:60)
+    at callMain (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:7031:15)
+    at doRun (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:7077:23)
+    at run (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:7092:5)
+    at runCaller (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:7018:19)
+    at removeRunDependency (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:6196:7)
+    at receiveInstance (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:6339:5)
+    at receiveInstantiationResult (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:6350:5)
+Thrown at:
+    at $21 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:1259:39)
+    at $25 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:2660:6)
+    at $24 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:1624:15)
+    at $33 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:3005:18)
+    at $3 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:674:3)
+    at $7 (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:765:6)
+    at ret.<computed> (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:6636:35)
+    at Module._main (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:6911:60)
+    at callMain (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:7031:15)
+    at doRun (/tmp/emscripten_test_wasm2js1_7slcjr46/test_asyncify_lists.js:7077:23)
+
```

**Review by kripken — APPROVED** [review]
lgtm. It would be difficult to get wasm2js to emit the same error here, as it ends up hitting a JS exceptions, not wasm. But the crucial thing is to get an exception, and it should be clear enough to help the user fix it...
