### ISSUE TITLE
Native optimizer fails to compile on OSX 10.10

### ISSUE THREAD

**Issue by floooh** [emscripten-core/emscripten#2997]
I just wanted to try the new native optimizer in incoming, and after Alon's first fix (https://groups.google.com/d/msg/emscripten-discuss/c_kXHYjgC_c/gIZMAHm0O1kJ) I'm now getting a compile error that the **unordered_set** header can't be found, the console dump is below. 

It's strange though that a trivial hello.cc compiled with clang does find the <unordered_set> header. Is there a way to display the compiler command line used for compiling the native optimizer? 

```
DEBUG    root: applying js optimization passes: ['asm', 'receiveJSON', 'eliminate', 'simplifyExpressions', 'emitJSON', 'minifyWhitespace']
chunkification: num funcs: 9 actual num chunks: 7 chunk size range: 1674340 - 664511
DEBUG    root: js optimizer using native
DEBUG    root: building native optimizer
In file included from /Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/optimizer/optimizer.cpp:7:
/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/optimizer/minijson.h:19:10: fatal error: 
      'unordered_set' file not found
#include <unordered_set>
         ^
1 error generated.
Traceback (most recent call last):
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1523, in <module>
    flush_js_optimizer_queue()
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1432, in flush_js_optimizer_queue
    run_passes(chunks[i], 'js_opts_' + str(i), just_split='receiveJSON' in chunks[i], just_concat='emitJSON' in chunks[i])
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/emcc", line 1395, in run_passes
    final = shared.Building.js_optimizer(final, passes, jcache, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/shared.py", line 1629, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, jcache, debug, extra_info, just_split, just_concat)
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 426, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 426, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 320, in run_on_js
    commands = map(lambda filename: [get_native_optimizer(), filename] + passes, filenames)
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 320, in <lambda>
    commands = map(lambda filename: [get_native_optimizer(), filename] + passes, filenames)
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 38, in get_native_optimizer
    return shared.Cache.get('optimizer.exe', create_optimizer, extension='exe')
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/cache.py", line 36, in get
    temp = creator()
  File "/Users/floh/projects/oryol/sdks/osx/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 36, in create_optimizer
    assert os.path.exists(output)
AssertionError
```
