### ISSUE TITLE
wasm-ld: linking two different copies of libc when PIC and MAIN_MODULE

### ISSUE THREAD

**Issue by pmp-p** [emscripten-core/emscripten#9516]
i checked for SIDE MODULE not being present, added -fPIC everywhere
but wasm-ld failed at program linking and don't have much other clue than
```
wasm-ld: error: duplicate symbol: fprintf
            defined in /opt/sdk/emsdk-upstream/.emscripten_cache/wasm-obj/libc.a(fprintf.c.o)
            defined in /opt/sdk/emsdk-upstream/.emscripten_cache/wasm-obj-pic/libc.a(fprintf.c.o)
```
the linker line seems perfectly legit https://wyz.fr/paste/5JB/raw.
but `-s MAIN_MODULE=1` pulls wasm-obj-pic/libc.a while `-lc` wants to pull the non pic ones ( emcc with `-static` or not ).

Pipeline was :
a bunch of .o => lib.a with $(AR) rcs $(LIBMICROPYTHON) $(OBJ) => emcc -s MAIN_MODULE=1 -static -o program.html main.c lib.a -ldl -lm -lc

removing either of those would not solve the dl* functions requirements i have for FFI.
i may not have control on .o compilation but i can extract more info if needed.

observed on :
 lastest-upstream  and tot-upstream

**Comment by kripken** [comment]
Is this a regression (did it work once)?

**Comment by sbc100** [comment]
Yes, this worked in 1.38.45.  I bisected back to #9436

**Comment by sbc100** [comment]
Yes, this is a regression.   Normally including a library twice is just fine.   But when `MAIN_MODULE=1` we put the whole command line in `--whole-archive --end-whole-archive`

**Comment by sbc100** [comment]
We used to ignore things like `-lc` completely.  #9436 starts to honor them.

**Comment by sbc100** [comment]
The problem is that when linking with LINKABLE (e.g. -s SIDE_MODULE or -s MAIN_MODULE), we wrap the whole link line in `--whole-archive` and `--no-whole-archive`.

It was always the case the specifying the same library twice in such a case would cause doubly defined symbols.  For example even back in 1.38.45 you would get this:

```
./emcc -s MAIN_MODULE=1 liblib.a liblib.a 
wasm-ld: error: duplicate symbol: main
>>> defined in liblib.a(hello.o)
>>> defined in liblib.a(hello.o)
```

But we use to have special case that ignored certain system libraries specified by the user so this used to work:

```
./emcc -s MAIN_MODULE=1 -lc -lc -lc
```

Because it used to be that all these of those arguments were ignored. 

Now `-lc` is meaningful and it can be found in the system lib direcotory so you will see the duplicate symbols just like for any other library.

I short I don't think we should try to fix this.    To fix this issue you can either remove the explicit `-lc` or disable the implicit one with `-nostdlib`.
