### PR TITLE
Updated WebGPU

### PR DESCRIPTION
**Pull request by Tandaradei**
**WIP**
Related issue: https://github.com/emscripten-core/emscripten/issues/11007
- Updated webgpu.h from webgpu-native (with changes like adding Reference/Release methods)
  - There some parts (functions on Adapter, Instance, Surface etc) that I just added as a comment, because I wasn't sure how they should be implemented. For example I haven't found anything on Surface/Instance in the specification.
- Manually updated WebGPU part of struct_info.json (couldn't figure out how to use the generator)
- Updated library_webgpu.js
  - Renamed all _binding_/_bindings_ to _entry_/_entries_ in `wgpuDeviceCreateBindGroupLayout `and `wgpuDeviceCreateBindGroup`
  - Added functions for QuerySet
  - Renamed all two part 64bit integers from _\<name\>\_l_/_\<name\>\_h_ to  _\<name\>\_low_/_<name\>\_high_ to match `defineI64Param `and `receiveI64ParamAsI32s`
  - Added `size `parameter to `setIndexBuffer `and `setVertexBuffer`
  - Changed default/required `PresentMode `from `VSync `to `Fifo`

I tested the changes with my pet project (https://github.com/Tandaradei/webgpu-wasm/tree/new-webgpu-version) which works fine in Chrome Canary 84.0.4133.0, but doesn't work in Firefox Nightly 77.0a1 (`TypeError: buffer.mapWriteAsync is not a function,_wgpuBufferMapWriteAsync`). 
The project isn't using all the features from WebGPU so I'm not sure if everything works (for example the new QuerySet).

### CODE REVIEW

**Comment by juj** [comment]
Hey, really cool to notice you are writing a bachelor's thesis about WebGPU @Tandaradei!

I have been trying to find a good stretch of time from other fronts to jump in to reviewing WebGPU as well. There are some hot questions we are pondering here at Unity:
1. What will the code size difference be between a WebGL 2-enabled renderer vs a WebGPU-enabled renderer? The API is a bit verbose in comparison to WebGL 2, making me wonder how it will translate to delivery size, especially on really small renderers.
2. Operating the WebGL 2 API is JavaScript garbage free at rendering time, meaning that calling the API functions will not cause temporary JS garbage units to be generated (in the hot paths/per-frame loop). JS GCs that stemmed from produced WebGL 1 garbage caused annoying stuttering with Unreal Engine 3 and 4 back in the day. Looking at the current library_webgpu.js implementation we have, there are a lot of places where it trashes. I wonder if those places will all be either cold, or if Emscripten layer will then be able to pool up all the JS objects to avoid trashing, so that WebGPU execution will also be garbage free at rendering time.
3. What will the main thread JS CPU utilization % be like for WebGPU vs WebGL 2?
4. What will the overall system Watts consumption be like for WebGPU vs WebGL 2?
5. How well does WebGPU execute in practice on avoiding general per-frame stalling/stuttering (due to shader compilation/texture/buffer upload delays etc. that WebGL 2 had)?

Perhaps some of those perspectives may be interesting for your research as well :) If you end up producing data points, would be curious to read!

Great work with getting on top of WebGPU with Emscripten! 

@kainino0x : on the note of point 5 above: is there any machinery to query if one is getting WebGPU-on-top-of-Vulkan vs WebGPU-on-top-of-GLES2/3 in a browser? I'd imagine e.g. shader compilation performance (and performance overrall..) will still be quite bad if browser needs to fall back to a GLES backend?

**Comment by Tandaradei** [comment]
Hey @juj,

I will be completely honest with you, I have no answer for any of your questions.
I like graphics programming and wanted to my bachelor thesis on something related to it. I have never done a GPU renderer before and have never even come close to WebGL, so I'm far from expert or even proficient on any of this topics. I started with the practical part of the thesis with implementing a (very simple) renderer to get a feeling for WebGPU and now I will slowly transition to the theoretical part.
I will take your points as inputs for my research but don't expect too much, I don't think my research will be as deep and detailed as you need it to be.


Does somebody know why there are 3 checks failing? From the error messages it seems like something WASM/SIMD related, but I have no idea what caused this to fail or how to fix it.

**Comment by sbc100** [comment]
There was some recent SIMD failures due to opcode renumbering that are not related to this PR.

I think just re-basing your change to origin/master (past #11058) should help

**Comment by kainino0x** [comment]
> @kainino0x : on the note of point 5 above: is there any machinery to query if one is getting WebGPU-on-top-of-Vulkan vs WebGPU-on-top-of-GLES2/3 in a browser? I'd imagine e.g. shader compilation performance (and performance overrall..) will still be quite bad if browser needs to fall back to a GLES backend?

By default WebGPU will most likely always be on Vulkan/D3D12/Metal (it is right now). If there ends up being a GL backend it will probably require an explicit "compatibility profile" flag.

> 2\. Looking at the current library_webgpu.js implementation we have, there are a lot of places where it trashes. I wonder if those places will all be either cold, or if Emscripten layer will then be able to pool up all the JS objects to avoid trashing, so that WebGPU execution will also be garbage free at rendering time.

This is an improvement I've been thinking about for the long term. Right now most of the garbage-heavy entry points are relatively cold, but we still have the inherent garbage from the API of bind group creation and command encoder / pass / command buffer creation, so I'd like the group to finish discussing that topic first (e.g. https://github.com/gpuweb/gpuweb/issues/214).

**Comment by kainino0x** [comment]
Re-merged master into your branch because somehow the diff was including commits from master.

File: src/library_webgpu.js [hunk 1]
```diff
@@ -933,6 +943,22 @@ var LibraryWebGPU = {
     var device = WebGPU["mgrDevice"].get(deviceId);
     return WebGPU.mgrShaderModule.create(device["createShaderModule"](desc));
   },
+  
+
```
Comment (kainino0x) [inline src/library_webgpu.js:947]: nit: extra blank line

File: src/struct_info.json [hunk 2]
```diff
@@ -1824,18 +1844,30 @@
...
+            "WGPUSurfaceDescriptorFromWindowsHWND": [
+                "nextInChain",
+                "hinstance",
+                "hwnd"
+            ],
+            "WGPUSurfaceDescriptorFromXlib": [
+                "nextInChain",
+                "display",
+                "window"
+            ],
```
Comment (kainino0x) [inline src/struct_info.json:1862]: nit: These are unused on the Web, so don't need to be included.

File: src/library_webgpu.js [hunk 3]
```diff
@@ -67,11 +67,11 @@
       // Assert descriptor is non-null, then that its nextInChain is null.
       var OffsetOfNextInChainMember = 0;
       return this.makeCheck(descriptor) + this.makeCheck(makeGetValue(descriptor, OffsetOfNextInChainMember, '*') + ' === 0');
-    },
+      },
```
Comment (kainino0x) [inline src/library_webgpu.js:70]: nit: extra indentation

File: src/library_webgpu.js [hunk 4]
```diff
@@ -933,6 +943,22 @@ var LibraryWebGPU = {
...
+
+  wgpuDeviceCreateQuerySet: function(deviceId, descriptor) {
+    {{{ gpu.makeCheckDescriptor('descriptor') }}}
+    var desc = {
+      "label": undefined,
+      "type": WebGPU.QueryType[
+        {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUQuerySetDescriptor.type) }}}],
+      "count": {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUQuerySetDescriptor.count) }}}
+    };
+    var labelPtr = {{{ makeGetValue('descriptor', C_STRUCTS.WGPUShaderModuleDescriptor.label, '*') }}};
```
Comment (kainino0x) [inline src/library_webgpu.js:956]:
```suggestion
    var labelPtr = {{{ makeGetValue('descriptor', C_STRUCTS.WGPUQuerySetDescriptor.label, '*') }}};
```
I almost missed this :)

File: src/struct_info.json (hunk 2 above)
Comment (Tandaradei) [reply src/struct_info.json:1862]: You mean the whole `WGPUSurfaceDescriptorFromMetalLayer`, -`WindowsHWND` and -`Xlib` structs?

File: system/include/webgpu/webgpu.h [hunk 5]
```diff
@@ -624,26 +661,22 @@ typedef struct WGPUSurfaceDescriptor {
 
 typedef struct WGPUSurfaceDescriptorFromHTMLCanvasId {
     WGPUChainedStruct const * nextInChain;
```
[the remark this answers is not in the document]
Comment (Tandaradei) [reply system/include/webgpu/webgpu.h:663]: So `nextInChain` for all the descriptors that are the first, and `chain` for all following in the chain? Then we have to adjust `makeCheckDescriptor` so it doesn't just check for `nextInChain` to be `NULL`

File: src/library_webgpu.js [hunk 6]
```diff
@@ -492,14 +501,14 @@ var LibraryWebGPU = {
 
   // wgpuDevice
 
-  // wgpuDeviceCreate*
-
-  wgpuDeviceCreateQueue: function(deviceId) {
+  wgpuDeviceGetDefaultQueue: function(deviceId) {
     assert(WebGPU.mgrQueue.objects.length === 1, 'there is only one queue');
```
[the remark this answers is not in the document]
Comment (Kangz) [reply src/library_webgpu.js]: It is supposed to refcount++

File: src/struct_info.json (hunk 2 above)
Comment (kainino0x) [reply src/struct_info.json]: Yup

File: src/library_webgpu.js [hunk 7]
```diff
@@ -65,16 +65,23 @@
     },
     makeCheckDescriptor: function(descriptor) {
       // Assert descriptor is non-null, then that its nextInChain is null.
+      // For descriptors that aren't the first in the chain (e.g ShaderModuleSPIRVDescriptor),
+      // there is no nextInChain pointer but a ChainedStruct object named chain.
+      // So we need to check if chain.nextInChain is null. As long as nextInChain and chain are both the 
+      // first member in the struct, descriptor.nextInChain and descriptor.chain.nextInChain should have the same offset (0)
```
Comment (kainino0x) [inline src/library_webgpu.js:71]: We do guarantee they both have offset 0, so this is OK.

File: src/library_webgpu.js [hunk 8]
```diff
@@ -502,9 +509,11 @@ var LibraryWebGPU = {
   // wgpuDevice
 
   wgpuDeviceGetDefaultQueue: function(deviceId) {
-    assert(WebGPU.mgrQueue.objects.length === 1, 'there is only one queue');
-    var device = WebGPU["mgrDevice"].get(deviceId);
-    return WebGPU.mgrQueue.create(device["defaultQueue"]);
+    if(WebGPU.mgrQueue.objects.length === 1) {
```
Comment (kainino0x) [inline src/library_webgpu.js:512]: This is a nice solution.

`=== 1` should work for the first device, but I think we can easily make this work for multiple devices now, with something like:
```suggestion
    if (WebGPU.defaultQueues[deviceId] === undefined) {
```

File: src/library_webgpu.js [hunk 9]
```diff
@@ -509,11 +509,19 @@ var LibraryWebGPU = {
...
+#if ASSERTIONS
+    assert(queueId != 0, 'got invalid queue');
+#endif
+    if(queueId === undefined) {
       var device = WebGPU["mgrDevice"].get(deviceId);
       WebGPU.defaultQueues[deviceId] = WebGPU.mgrQueue.create(device["defaultQueue"]);
+      queueId = WebGPU.defaultQueues[deviceId];
+    }
+    else {
+      WebGPU.mgrQueue.reference(queueId);
```
Comment (kainino0x) [inline src/library_webgpu.js:522]: Ah yes, forgot about this, thanks :)

**Comment by kainino0x** [comment]
> It would be ideal if we could include at least one more change: the refactor of WGPUShaderModuleDescriptor. Without this it won't be possible for an app to build the same code against both Dawn and Emscripten. (There may be other issues I'm missing, but this is the most noticeable.)

I'd still like to resolve this one before merging (I could take care of it if needed).

**Comment by Tandaradei** [comment]
> > It would be ideal if we could include at least one more change: the refactor of WGPUShaderModuleDescriptor. Without this it won't be possible for an app to build the same code against both Dawn and Emscripten. (There may be other issues I'm missing, but this is the most noticeable.)
> 
> I'd still like to resolve this one before merging (I could take care of it if needed).

So no more `code`/`codeSize` in `WGPUShaderModuleDescriptor`? And it chains to a specific (_SPIRV_/_WGSL_) shader module descriptor? Like the surface descriptors?

What has to be done to finish this up? :)

PS: Why is there no `size` member in `WGPUShaderModuleWGSLDescriptor `?

**Comment by kainino0x** [comment]
> So no more `code`/`codeSize` in `WGPUShaderModuleDescriptor`? And it chains to a specific (_SPIRV_/_WGSL_) shader module descriptor? Like the surface descriptors?

Yup, exactly. Sorry, I should point to an example.
https://cs.chromium.org/chromium/src/third_party/dawn/src/utils/WGPUHelpers.cpp?l=54&rcl=94efed23e7fb262bfcadb0dace5a873a7abfdb07

> What has to be done to finish this up? :)

- Remove  `code`/`codeSize` from `WGPUShaderModuleDescriptor` in header and struct_info
- Deconstruct the SPIRV chained object in `wgpuDeviceCreateShaderModule`
- Optionally also support the WGSL chained object

> PS: Why is there no `size` member in `WGPUShaderModuleWGSLDescriptor `?

WGSL is text so it's passed as a null-terminated string.

**Comment by Tandaradei** [comment]
> Yup, exactly. Sorry, I should point to an example.
> https://cs.chromium.org/chromium/src/third_party/dawn/src/utils/WGPUHelpers.cpp?l=54&rcl=94efed23e7fb262bfcadb0dace5a873a7abfdb07

In your linked example, shouldn't there be a `ChainedStruct` wrapped around the pointer to the SPIRV descriptor?
In my understanding it should look like this (C instead of C++):
```C
WGPUShaderModuleSPIRVDescriptor sm_desc = {
  .codeSize = spv_source_size / sizeof(uint32_t),
  .code = (const uint32_t*)spv_source_data
};
WGPUShaderModuleDescriptor sm_wrapper = {
  .nextInChain = &(WGPUChainedStruct){
    .next = (WGPUChainedStruct const*)&sm_desc,
    .sType = WGPUSType_ShaderModuleSPIRVDescriptor
  },
};
WGPUShaderModule module = wgpuDeviceCreateShaderModule(device, &sm_wrapper);
```

**Comment by kainino0x** [comment]
It's not exactly like your C code. Sorry, that example used the C++ wrapper so it's not exactly the same. Here's another example which I forgot about:
https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/webgpu/gpu_shader_module.cc?l=21&rcl=a47ddf858f207179e5a179b73c4042d690e76823
Hopefully this is more helpful.

File: src/library_webgpu.js [hunk 10]
```diff
@@ -930,20 +947,38 @@ var LibraryWebGPU = {
...
     };
     var labelPtr = {{{ makeGetValue('descriptor', C_STRUCTS.WGPUShaderModuleDescriptor.label, '*') }}};
     if (labelPtr) desc["label"] = UTF8ToString(labelPtr);
 
+    if(sType === {{{ gpu.SType.ShaderModuleSPIRVDescriptor }}}) {
+      var count = {{{ gpu.makeGetU32('nextInChainPtr', C_STRUCTS.WGPUShaderModuleSPIRVDescriptor.codeSize) }}};
+      var start = {{{ makeGetValue('nextInChainPtr', C_STRUCTS.WGPUShaderModuleSPIRVDescriptor.code, '*') }}};
+      desc["code"] = HEAPU32.subarray(start >> 2, (start >> 2) + count);
+    }
+    else if(sType === {{{ gpu.SType.ShaderModuleWGSLDescriptor }}}) {
```
Comment (kainino0x) [inline src/library_webgpu.js:972]: nit:
```suggestion
    if (sType === {{{ gpu.SType.ShaderModuleSPIRVDescriptor }}}) {
      var count = {{{ gpu.makeGetU32('nextInChainPtr', C_STRUCTS.WGPUShaderModuleSPIRVDescriptor.codeSize) }}};
      var start = {{{ makeGetValue('nextInChainPtr', C_STRUCTS.WGPUShaderModuleSPIRVDescriptor.code, '*') }}};
      desc["code"] = HEAPU32.subarray(start >> 2, (start >> 2) + count);
    } else if (sType === {{{ gpu.SType.ShaderModuleWGSLDescriptor }}}) {
```

File: src/library_webgpu.js [hunk 11]
```diff
@@ -502,9 +509,19 @@ var LibraryWebGPU = {
...
+    var queueId = WebGPU.defaultQueues[deviceId];
+#if ASSERTIONS
+    assert(queueId != 0, 'got invalid queue');
+#endif
+    if(queueId === undefined) {
+      var device = WebGPU["mgrDevice"].get(deviceId);
+      WebGPU.defaultQueues[deviceId] = WebGPU.mgrQueue.create(device["defaultQueue"]);
+      queueId = WebGPU.defaultQueues[deviceId];
+    }
+    else {
```
Comment (kainino0x) [inline src/library_webgpu.js:521]: nit:
```suggestion
    if (queueId === undefined) {
      var device = WebGPU["mgrDevice"].get(deviceId);
      WebGPU.defaultQueues[deviceId] = WebGPU.mgrQueue.create(device["defaultQueue"]);
      queueId = WebGPU.defaultQueues[deviceId];
    } else {
```

**Comment by kainino0x** [comment]
Since I don't have any good test cases for this, let me see if I can find someone to try this out on their codebase to make sure everything seems working before landing :)

File: src/library_webgpu.js [hunk 12]
```diff
@@ -559,7 +584,6 @@ var LibraryWebGPU = {
     var desc = {
       "label": undefined,
       "size": WebGPU.makeExtent3D(descriptor + {{{ C_STRUCTS.WGPUTextureDescriptor.size }}}),
-      "arrayLayerCount": {{{ gpu.makeGetU32('descriptor', C_STRUCTS.WGPUTextureDescriptor.arrayLayerCount) }}},
```
Comment (Kangz) [inline src/library_webgpu.js:562]: This shouldn't be removed for now, it isn't part of the [PSA](https://hackmd.io/Et7xlhoaThmi8dEX_s-xSw?view) we sent, and it breaks the possibility to have applications that target both Dawn and emscripten at the same time. It was found by @hugoam.

File: src/struct_info.json [hunk 13]
```diff
@@ -1909,7 +1925,6 @@
                 "usage",
                 "dimension",
                 "size",
-                "arrayLayerCount",
```
Comment (Kangz) [inline src/struct_info.json:1912]: ditto

**Comment by hugoam** [comment]
To be discussed with @kainino0x and @Kangz
But eventually, if Emscripten wants to stay compatible with Dawn's headers, I isolated the necessary fixes that must be applied to this PR: https://github.com/hugoam/emscripten/commit/d549969c678690a47828396f579a8a7061e09d98
This reverts almost all the occlusion query work. Unfortunately we can't keep it if we want to use Dawn's header, since it doesn't exist there yet. We can't either keep it in `library_webgpu.js` because the library compiler tries to compile it against non-existing structs (commented out for now in `struct_info.json` because they don't exist in Dawn's `webgpu.h`)

Aside from that, and with those fixes, the PR works as expected
My personal advice would be: keep the occlusion query work in a separate branch until Dawn implements it, and add it only then. It seems unlikely that any other implementer would have occlusion queries before Dawn anyway ?

**Comment by juj** [comment]
> My personal advice would be: keep the occlusion query work in a separate branch until Dawn implements it, and add it only then.

Is this a case where the spec headers already define upcoming work (occlusion queries have already been added to the spec and headers?), but Dawn hasn't just implemented them? Do we expect that the content in the headers will stay the same?

If so, then let's not delete valid work that has already been taken, but instead can add comments to webgpu.h and library_webgpu.js along the lines of `// note: no backend implementation available, not yet tested`. That way once Dawn does add them, there is no need to take action to add the support, but can just remove the comments once someone gets around to verifying the code paths.

If on the other hand that is work that is not likely to stay the same, then dropping it sounds viable?

**Comment by hugoam** [comment]
The problem is that there currently exists no other `webgpu_cpp` implementation than the one in Dawn. So the only way Emscripten slightly supports an application written against a C++ API of WebGPU is by sticking to Dawn's version of the header, which is what Emscripten own header is, historically, until that PR.

If you merge this PR as-is, my application will not be able support WebGPU through Emscripten anymore, because it is built against the C++ API which was removed from Emscripten before WebGPU initial support was merged.

- one option is for Emscripten to provide a version of `webgpu_cpp` that works with the `webgpu.h` header it chose. (which would allow you to keep the Occlusion Query work, but has a cost)
- another option is to stick to Dawn's version of `webgpu.h`, which prevents the Occlusion Query work to go in as well

**Comment by juj** [comment]
Hmm, if I understood the situation correctly, it does seem like the best way forward would be to include `webgpu_cpp` into this repository that'd match `webgpu.h`, having API dependencies to external code does seem awkward.

> Even though writing that wrapper is a simple task that can be largely automated, Dawn is the only one to provide one for now.

Do you know if Dawn autogenerates its webgpu_cpp wrapper? Or is it all currently hand-maintained?

**Comment by Kangz** [comment]
> Do you know if Dawn autogenerates its webgpu_cpp wrapper? Or is it all currently hand-maintained?

All of `webgpu.h`, `webgpu_cpp.h`, `webgpu_cpp.cpp` and parts of `library_webgpu.js` and `struct_info.json` are autogenerated from [these templates](https://dawn.googlesource.com/dawn/+/refs/heads/master/generator/templates/) and [`dawn.json`](https://dawn.googlesource.com/dawn/+/refs/heads/master/dawn.json). We have a patch to apply to generate "upstream" webgpu-native/webgpu-header's `webgpu.h` and maybe @kainino0x has a patch to apply to generate the emscripten parts.

**Comment by hugoam** [comment]
Would it by thinkable to add some fields in `dawn.json` so that both webgpu-native and dawn's flavor can be generated from the same file, instead of patching it ?
e.g `"visibility": "dawn"` and `"visibility": "webgpu-native"` for fields, classes and functions that belong specifically (or temporarily) to one or another ?

**Comment by Kangz** [comment]
I'm not too keen on adding conditionals to `dawn.json` like this. Instead webgpu-native should probably have its own copy of the generator. When WebGPUv1 is out, there will be less issues like this with backwards incompatible changes.

**Comment by kainino0x** [comment]
Thanks for the patch Hugo, I'm going to make some tweaks to it and push it to this branch. I think we'll be ready to merge then. (I may not be able to get this done today, we'll see.)

**Comment by Kangz** [comment]
Ah, @hugoam added back some things so `webgpu_cpp.cpp` compiles. That explains the question about having Dawn support visibilities in `dawn.json`. We need to figure out the exact details, but maybe we could have best effort annotations that make it generate a `webgpu_cpp` that matches the current emscripten. (that would only be needed until WebGPU v1, and maybe while working on WIP extensions).

**Comment by kainino0x** [comment]
Ohh I see. I guess we should just exactly match Dawn here for the moment then.

**Comment by kainino0x** [comment]
@hugoam I merged your changes and added an extra commit on top. Could you review and verify my changes?
https://github.com/emscripten-core/emscripten/pull/11067/commits/5f83f1f16def4cc82a46b70616fef07c906de017

**Comment by kainino0x** [comment]
Sorry, realized that change wouldn't compile with webgpu_cpp.cpp (I ctrl-f'd wrong the first time).

https://github.com/emscripten-core/emscripten/pull/11067/commits/f494f63fe93784f8dce213e2bf53ab55f2490f66
now.

**Comment by kainino0x** [comment]
BTW I think we should put webgpu_cpp in both webgpu-headers and Emscripten eventually, but we'll do that later.

File: src/struct_info.json [hunk 14]
```diff
@@ -1857,14 +1873,14 @@
                 "nextInChain",
                 "label",
                 "layout",
-                "bindingCount",
```
Comment (hugoam) [inline src/struct_info.json:1860]: Unless I'm mistaken, I don't think it will work like this. Those definitions here determine the offsets applied in the JS wrapper to get to the underlying values in the C/C++ struct.
The new fields have been added *after* the deprecated fields, so by removing those from this mapping, the new offsets of `entryCount` and `entries` JS side will actually map to the offsets of the old fields `bindingCount` and `bindings` on the C struct, which are expected to not have been set, since we're expecting the non-deprecated usage here.
The JS value of those fields will therefore be garbage (again, unless I missed something).
It's kind of a stroke of bad luck, since if the new fields had been added *before* the deprecated fields, it would "magically" work (but I wouldn't like to be counting of that either and it could mess with the offsets of the fields right after if there are any).

**Comment by kainino0x** [comment]
The list of members in struct_info is not enough to compute the offsets (it doesn't know the types). I think how this works is it calls offsetof in C and saves the result. So I'm pretty sure this still would work.

**Comment by hugoam** [comment]
Ahhh, I must have conflated some of the errors I faced when trying to get this to work with an overly naive explanation of how Emscripten works then ! I suppose it's all good in that case

**Comment by hugoam** [comment]
Now Dawn has just removed the deprecated fields. But we'll do a follow-up PR I suppose 😄

**Comment by kainino0x** [comment]
Yup, we knew we would need another PR here :)

I wanted to get this landed as we're about to start removing the deprecated fields from Blink as well, so they won't be exposed to JS anymore, and this patch is needed for Emscripten'd content to work on Chrome.

**Comment by hugoam** [comment]
Just tried building bgfx examples with Emscripten@master and it works as expected 😄 
(the up to date links are at https://github.com/bkaradzic/bgfx/issues/2023)

**Comment by kainino0x** [comment]
Awesome!
