### ISSUE TITLE
256-bit AVX intrinsics support

### ISSUE THREAD

**Issue by jiepan-intel** [emscripten-core/emscripten#21684]
Compile existing x86 SSE/AVX SIMD code into WASM SIMD is very attractive, developer can reuse existing library without rewrite it.
However currently only 128-bit subset of the AVX intrinsics are supported, many existing code cannot meet this restriction.
Adding 256-bit AVX intrinsics support will expand the applicable scenarios and may also increase performance.
Does emscripten have a plan for this?

Currently Google [Highway](https://github.com/google/highway) supports WASM_EMU256 (a 2x unrolled version of wasm128) target, 
A [re-vectorize](https://bugs.chromium.org/p/v8/issues/detail?id=12716) optimization phase is being developed in Google V8 JS engine, which can pack two SIMD128 nodes into one SIMD256 node.

Sample code for AVX intrinsics support:

```
typedef struct Vec256 {
  __m128 v0;
  __m128 v1;
}__m256;

static __inline__ __m256 __attribute__((__always_inline__, __nodebug__))
_mm256_add_ps(__m256 __a, __m256 __b) {
    __m256 c;
    c.v0 = (__m128)wasm_f32x4_add((v128_t)__a.v0, (v128_t)__b.v0);
    c.v1 = (__m128)wasm_f32x4_add((v128_t)__a.v1, (v128_t)__b.v1);
    return c;
}
```

**Comment by jkl1337** [comment]
The current header fails to work with the C compiler, proposed fix in #22850

**Comment by peterhirn** [comment]
After the latest fixes in `v4.0.2` I'm still unable to build https://github.com/P-H-C/phc-winner-argon2 with emulated 256-bit wide intrinsics.

- PR https://github.com/phi-ag/argon2/pull/106
- Action https://github.com/phi-ag/argon2/actions/runs/13049464651/job/36406283414?pr=106

```
src/opt.c:83:46: error: incompatible pointer types passing 'const __m256i *' to parameter of type 'const __m256i_u *' [-Werror,-Wincompatible-pointer-types]
   83 |                 state[i], _mm256_loadu_si256((const __m256i *)ref_block->v + i));
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tlively** [comment]
@peterhirn, it looks like you should be able to disable that particular error with `-Wno-error=incompatible-pointer-types` as a workaround.

**Comment by kleisauke** [comment]
I think this was implemented via PR #22430 and #23035.
