### ISSUE TITLE
MAME Compiles into WASM Fine in Emscripten 2.0.8. Does not in Emscripten 2.0.12

### ISSUE THREAD

**Issue by historicalsource** [emscripten-core/emscripten#13436]
I'm sorry I can't nail down which version has the bug. 

The whole shebang compiles MAME 0.228 fine in Emscripten 2.0.8. MAME is here:
https://github.com/mamedev/mame/releases/tag/mame0228

We compile using this command:

   emmake make -j4 SUBTARGET=1942 SOURCES=src/mame/drivers/1942.cpp NOWERROR=1 REGENIE=1

(There's many more subtargets, but this fails the same as any of them.)

Here's the errors it shoots out:

[ 98%] Linking CXX executable hb-ot-tag.js
[100%] Linking CXX executable main.js
[100%] Built target hb-ot-tag
[100%] Built target test-size-params
[100%] Built target test-buffer-serialize
[100%] Built target main
[100%] Built target test-would-substitute
[100%] Built target test-test
Install the project...
-- Install configuration: "Release"
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-version.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-blob.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-buffer.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-common.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-deprecated.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-face.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-font.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-set.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-shape.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-shape-plan.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-unicode.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ot.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ot-font.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ot-layout.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ot-math.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ot-shape.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ot-tag.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ot-var.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz/hb-ft.h
-- Installing: /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/lib/libharfbuzz.a
cache:INFO:  - ok
system_libs:INFO: retrieving port: sdl2_ttf from https://hg.libsdl.org/SDL_ttf/archive/703ebc7c66fd.zip
system_libs:INFO: unpacking port: sdl2_ttf
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2_ttf.a... (this will be cached in "/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2_ttf.a" for subsequent builds)
cache:INFO:  - ok
In file included from ../../../../../src/emu/emu.h:21:
In file included from /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/list:183:
In file included from /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/memory:653:
In file included from /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/typeinfo:60:
In file included from /1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/exception:81:
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:100:9: error: no member named 'div_t' in the global namespace
using ::div_t;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:101:9: error: no member named 'ldiv_t' in the global namespace
using ::ldiv_t;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:103:9: error: no member named 'lldiv_t' in the global namespace
using ::lldiv_t;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:105:9: error: no member named 'atof' in the global namespace
using ::atof;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:106:9: error: no member named 'atoi' in the global namespace
using ::atoi;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:107:9: error: no member named 'atol' in the global namespace
using ::atol;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:109:9: error: no member named 'atoll' in the global namespace
using ::atoll;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:111:9: error: no member named 'strtod' in the global namespace
using ::strtod;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:112:9: error: no member named 'strtof' in the global namespace
using ::strtof;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:113:9: error: no member named 'strtold' in the global namespace
using ::strtold;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:114:9: error: no member named 'strtol' in the global namespace
using ::strtol;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:116:9: error: no member named 'strtoll' in the global namespace
using ::strtoll;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:118:9: error: no member named 'strtoul' in the global namespace
using ::strtoul;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:120:9: error: no member named 'strtoull' in the global namespace
using ::strtoull;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:122:9: error: no member named 'rand' in the global namespace
using ::rand;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:123:9: error: no member named 'srand' in the global namespace
using ::srand;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:124:9: error: no member named 'calloc' in the global namespace
using ::calloc;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:125:9: error: no member named 'free' in the global namespace
using ::free;
      ~~^
/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/cstdlib:126:9: error: no member named 'malloc' in the global namespace
using ::malloc;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
em++: error: '/1/EMSCRIPTEN/emsdk/upstream/bin/clang++ -DEMSCRIPTEN -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -emscripten-cxx-exceptions-allowed=_ZN15running_machine17start_all_devicesEv,_ZN12cli_frontend7executeEiPPc,_ZN8chd_file11open_commonEb,_ZN8chd_file13read_metadataEjjRNSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE,_ZN8chd_file13read_metadataEjjRNSt3__26vectorIhNS0_9allocatorIhEEEE,_ZNK19netlist_mame_device19base_validity_checkER16validity_checker -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -iwithsysroot/include/SDL -Xclang -isystem/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/SDL2 -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz -DTTF_USE_HARFBUZZ=1 -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration --sysroot=/1/EMSCRIPTEN/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -MMD -MP -MP -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/include -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/include/compat -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/include/libc -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/lib/libcxxabi/include -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util -pipe -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-error=deprecated-declarations -Wno-cast-align -Wno-tautological-compare -Wno-unused-value -Wno-constant-logical-operand -fdiagnostics-show-note-include-stack -Wno-unknown-warning-option -Wno-extern-c-compat -Wno-unknown-attributes -Wno-ignored-qualifiers -Wno-pragma-pack -Wno-xor-used-as-pow -Wno-self-assign-field -Wno-format-security -Wno-inline-new-delete -Wno-absolute-value -std=gnu89 -Wno-implicit-function-declaration -std=c++14 -Woverloaded-virtual -x c++-header -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/include -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/include/compat -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/include/libc -I/1/EMSCRIPTEN/emsdk/upstream/emscripten/system/lib/libcxxabi/include -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util -c ../../../../../src/emu/emu.h -o ../../../../asmjs/obj/Release/emu.h.gch' failed (1)
make[2]: *** [precompile.make:317: ../../../../asmjs/obj/Release/emu.h.gch] Error 1
make[1]: *** [Makefile:82: precompile] Error 2
make: *** [makefile:1352: asmjs] Error 2
root@teamarchive1:/1/MAME/mame#

**Comment by kripken** [comment]
I'm not sure what's going on here, but I narrowed this down to
```
-I/../emscripten/system/include/compat
```
Removing that from the command avoids the problem.

Is that added somewhere in the MAME build script? Then removing it should fix things. Emscripten by itself doesn't issue such paths any more, it should always point to the sysroot after @sbc100 recent work (which is indeed in that range of versions).

**Comment by sbc100** [comment]
Actually I think the compat dir is the exception.  We still pass it but it will looks like -withsysroot... see: https://github.com/emscripten-core/emscripten/blob/ffe1c7945c28eccfe8a7938ce91019311def7d83/tools/shared.py#L510

**Comment by kripken** [comment]
@sbc100 correct, we pass it, but in the sysroot. So we never pass a path to `system/` in the emscripten dir outside of the sysroot.

I am not sure why manually passing a path to `system/` breaks things like this, but I guess that's just dangerous to do in the new model?

**Comment by kripken** [comment]
Tiny STR for the issue:
```cpp
#include <list>
```
```
./emcc a.cpp -I`pwd`/./system/include/compat

/home/azakai/Dev/emscripten/cache/sysroot/include/c++/v1/cstdlib:100:9: error: no member named 'div_t' in the global namespace
using ::div_t;
      ~~^
```

**Comment by eahumada** [comment]
I wonder if there is a fix or workaround for this issue, I'm see the same problem when try to compile with emscripten 2.0.16 on Mac OSX catalina:

```
(mame) eahumada@TARDIS mame % emmake make SUBTARGET=a130xe SOURCES=src/mame/drivers/atari400.cpp
make: make SUBTARGET=a130xe SOURCES=src/mame/drivers/atari400.cpp
Clang 13.0.0 detected
Precompiling src/emu/emu.h...
In file included from ../../../../../src/emu/emu.h:21:
In file included from /usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/list:183:
In file included from /usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/memory:653:
In file included from /usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/typeinfo:60:
In file included from /usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/exception:81:
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:100:9: error: no member named 'div_t' in the global namespace
using ::div_t;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:101:9: error: no member named 'ldiv_t' in the global namespace
using ::ldiv_t;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:103:9: error: no member named 'lldiv_t' in the global namespace
using ::lldiv_t;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:105:9: error: no member named 'atof' in the global namespace
using ::atof;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:106:9: error: no member named 'atoi' in the global namespace
using ::atoi;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:107:9: error: no member named 'atol' in the global namespace
using ::atol;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:109:9: error: no member named 'atoll' in the global namespace
using ::atoll;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:111:9: error: no member named 'strtod' in the global namespace
using ::strtod;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:112:9: error: no member named 'strtof' in the global namespace
using ::strtof;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:113:9: error: no member named 'strtold' in the global namespace
using ::strtold;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:114:9: error: no member named 'strtol' in the global namespace
using ::strtol;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:116:9: error: no member named 'strtoll' in the global namespace
using ::strtoll;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:118:9: error: no member named 'strtoul' in the global namespace
using ::strtoul;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:120:9: error: no member named 'strtoull' in the global namespace
using ::strtoull;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:122:9: error: no member named 'rand' in the global namespace
using ::rand;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:123:9: error: no member named 'srand' in the global namespace
using ::srand;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:124:9: error: no member named 'calloc' in the global namespace
using ::calloc;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:125:9: error: no member named 'free' in the global namespace
using ::free;
      ~~^
/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/c++/v1/cstdlib:126:9: error: no member named 'malloc' in the global namespace
using ::malloc;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
em++: error: '/usr/local/opt/emscripten/libexec/llvm/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -emscripten-cxx-exceptions-allowed=_ZN15running_machine17start_all_devicesEv,_ZN12cli_frontend7executeEiPPc,_ZN8chd_file11open_commonEb,_ZN8chd_file13read_metadataEjjRNSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE,_ZN8chd_file13read_metadataEjjRNSt3__26vectorIhNS0_9allocatorIhEEEE,_ZNK19netlist_mame_device19base_validity_checkER16validity_checker -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=16 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -flegacy-pass-manager -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL -I/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/freetype2/freetype -Xclang -isystem/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot/include/SDL2 -I/usr/local/Cellar/emscripten/2.0.16/libexec/cache/ports-builds/harfbuzz/include/harfbuzz -DTTF_USE_HARFBUZZ=1 --sysroot=/usr/local/Cellar/emscripten/2.0.16/libexec/cache/sysroot -Xclang -iwithsysroot/include/compat -MMD -MP -MP -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/include -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/include/compat -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/include/libc -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/lib/libcxxabi/include -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util -pipe -Werror -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -fdiagnostics-show-note-include-stack -Wno-cast-align -Wno-constant-logical-operand -Wno-extern-c-compat -Wno-ignored-qualifiers -Wno-pragma-pack -Wno-tautological-compare -Wno-unknown-attributes -Wno-unknown-warning-option -Wno-unused-value -Wno-xor-used-as-pow -Wno-self-assign-field -Wno-format-security -Wno-inline-new-delete -Wno-absolute-value -std=gnu89 -Wno-implicit-function-declaration -std=c++17 -Woverloaded-virtual -x c++-header -DNDEBUG -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/include -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/include/compat -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/include/libc -I/usr/local/Cellar/emscripten/2.0.16/libexec/system/lib/libcxxabi/include -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util -c ../../../../../src/emu/emu.h -o ../../../../asmjs/obj/Release/emu.h.gch' failed (1)
make[2]: *** [../../../../asmjs/obj/Release/emu.h.gch] Error 1
make[1]: *** [precompile] Error 2
make: *** [asmjs] Error 2
emmake: error: 'make SUBTARGET=a130xe SOURCES=src/mame/drivers/atari400.cpp' failed (2)
```

**Comment by eahumada** [comment]
Fixed on Mac OSX catalina, removing brew emscripten 2.0.16 and installing 2.0.8 with emsdk:
```
$ brew remove emscripten
$ brew clean up
$ ./emsdk install 2.0.8
$./emsdk activate 2.0.8
$ source ../../emscripten/emsdk/emsdk_env.sh
$ emmake make SUBTARGET=a800xl SOURCES=src/mame/drivers/atari400.cpp
...
Linking a800xl.bc...
...
```
Generating all the .js and wasm files.

**Comment by sbc100** [comment]
Installing 2.0.8 isn't actually a fix for the issue.

Can you confirm if installing 2.0.16 via emsdk works?  In which case we can be sure this is a homebrew issue.

**Comment by historicalsource** [comment]
It's not a homebrew issue. I don't use homebrew and I'm using Ubuntu to do
this.

**Comment by sbc100** [comment]
This is an upstream issue with mame.   `scripts/toolchain.lua` is adding include directories to the build where is shouldn't.   These include directories are part of the compiler itself and should not added manually:

```
    includedirs {                                                                   
      "$(EMSCRIPTEN)/system/include",                                               
      "$(EMSCRIPTEN)/system/include/compat",                                                                                  
      "$(EMSCRIPTEN)/system/include/libc",                                          
      "$(EMSCRIPTEN)/system/lib/libcxxabi/include",                                 
    }
```

The above snippet should be removed upstream.

**Comment by eahumada** [comment]
I started with 2.0.16 installed with emsdk and have the same issue.

**Comment by eahumada** [comment]
> Installing 2.0.8 isn't actually a fix for the issue.
> 
> Can you confirm if installing 2.0.16 via emsdk works? In which case we can be sure this is a homebrew issue.

My first test was with 2.0.16 installed with emsdk, then I try homebrew, in both cases the same issue.

Finally with emsdk going back to 2.0.8 solves the problem.

**Comment by sbc100** [comment]
I believe this issue can be closed since there is simple upstream fix.   Please comment/reopen if your disagree.

**Comment by DopefishJustin** [comment]
@sbc100 Thanks, this change has been committed upstream: https://github.com/mamedev/mame/commit/6462fb5e0097a1ce3c7fe9b538cc3bbd4ef5e50a
