### PR TITLE
Fix emcc_args in test_benchmark.py

### LINKED ISSUE #9006: test_benchmark.py's setUpClass is broken
```console
$ python tests/runner.py benchmark
...
======================================================================
ERROR: setUpClass (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/gzchen/waterfall/src/work/emscripten/tests/test_benchmark.py", line 354, in setUpClass
    self.emcc_args += [OPTIMIZATIONS]
AttributeError: type object 'benchmark' has no attribute 'emcc_args'

----------------------------------------------------------------------
Ran 0 tests in 0.081s

FAILED (errors=1)
```

This appears to have been caused by c5c1b815c1ac6f244459df87842e1e20c4c69aeb.

### PR DESCRIPTION
**Pull request by quantum5**
Fixes #9006.

### CODE REVIEW

**Comment by quantum5** [comment]
#8834 seems like a better fix.
