### ISSUE TITLE
test_benchmark.py's setUpClass is broken

### ISSUE THREAD

**Issue by quantum5** [emscripten-core/emscripten#9006]
```console
$ python tests/runner.py benchmark
...
======================================================================
ERROR: setUpClass (test_benchmark.benchmark)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/gzchen/waterfall/src/work/emscripten/tests/test_benchmark.py", line 354, in setUpClass
    self.emcc_args += [OPTIMIZATIONS]
AttributeError: type object 'benchmark' has no attribute 'emcc_args'

----------------------------------------------------------------------
Ran 0 tests in 0.081s

FAILED (errors=1)
```

This appears to have been caused by c5c1b815c1ac6f244459df87842e1e20c4c69aeb.

**Comment by sbc100** [comment]
Hmm.. that variable should be renamed from `self` to `cls` and that line should be moved to the per-test `setUp` function.

**Comment by sbc100** [comment]
You already did it :)

**Comment by quantum5** [comment]
Fixed in #8834.
